### ISSUE TITLE
Move repository to their own organization

### ISSUE THREAD

**Issue by ogarcia** [ultrasonic/ultrasonic#10]
@Tapchicoma I claim to GitHub the `ultrasonic` organization for better fine grained permissions to repository and I invite you to are a full member.

Please confirm me that this is fine and I move this repository to new org to work from there.

**Comment by Tapchicoma** [comment]
I think it is a great idea. Totally fine with it.

**Comment by ogarcia** [comment]
Ok. Repo moved!!! :wink:
