### ISSUE TITLE
Add an option to support self-signed or non-valid https server certificates

### ISSUE THREAD

**Issue by ogarcia** [ultrasonic/ultrasonic#100]
At this moment if the XXsonic server are using a non-valid/self-signed https certificate, Ultrasonic cannot connect with them giving a _network error_.

Will be interesting add an option (disabled by default) to ignore server certificate and connect anyway.

This bug may be related with #99

**Comment by TcM1911** [comment]
Maybe also worth adding a more descriptive error message.
