### ISSUE TITLE
Use an online tool for translations

### ISSUE THREAD

**Issue by ogarcia** [ultrasonic/ultrasonic#102]
I think that is better use a online tool like [Transifex][1], [Crowdin][2] or any others for manage app translations.

What you consider that is better. All opinions are welcome!!

[1]: https://www.transifex.com/
[2]: https://crowdin.com/

**Comment by prschopf** [comment]
I do some apps translations using Transifex but I *think* its not a free tool. Anyways, any online solution will be great.

**Comment by Tapchicoma** [comment]
Possible candidate: https://weblate.org/en/hosting/

Free for open-source software.

**Comment by Tapchicoma** [comment]
According to [Transifex pricing FAQ](https://www.transifex.com/pricing/):

> What are the basic requirements to qualify as an Open Source account?
>
> We are proud and humbled to be hosting the largest Open Source translation community in the world. We offer Transifex for free to Open Source projects that have no funding, revenue, and/or commercialization model. If you have a question whether your organization qualifies for our Open Source program, please contact us.

**Comment by ogarcia** [comment]
Yes, we enter in Transifex Open Source category. I think that we must choose between Weblate and Transifex.

**Comment by Tapchicoma** [comment]
Another candidate: https://lokalise.co/

>  What is the offer for open source projects?
> Let us know about your open source project and get a lifetime free Enterprise plan.

**Comment by Tapchicoma** [comment]
For me choosing criteria will be:
* Ease of upload/download translation strings (preferably using gradle plugin)
* Ease for collaborators to update translations

**Comment by ogarcia** [comment]
I'm looking for automate tools of translation platforms and I think that most complete (and easy for use) is Transifex.

As can see in [this example that is using WhisperSystems][1], is very simple to integrate our project into Transifex translation flow. I ask in sales for opt-in to Open Source model.

[1]: https://github.com/WhisperSystems/Signal-Android/blob/master/.tx/config

**Comment by ogarcia** [comment]
Added info about Contributing Translations with Transifex into [CONTRIBUTING.md](https://github.com/ultrasonic/ultrasonic/blob/master/CONTRIBUTING.md).

Now we need to integrate it in circleci to close this issue.

**Comment by Tapchicoma** [comment]
I think we also need to add cron job (CircleCI supports [it](https://circleci.com/docs/2.0/configuration-reference/#schedule)) that will pull translations from Transifex and create new Pull Request.

**Comment by prschopf** [comment]
@ogarcia 

Will you do the same to [Open Sudoku](https://github.com/ogarcia/opensudoku)?

**Comment by ogarcia** [comment]
@Tapchicoma The problem of make that Circle CI create a new PR is that we must give write permissions to it's deploy key and this may be a security problem.

I think that is better simply run the TX tool `tx pull -a` when we want, for example before tagging a new release, or simply use a [git hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) `post-merge` in our machines.

@prschopf no because Open Sudoku is a very small project that is finished and will not receive more significative changes and use Transifex for it is kill flies with cannons. Besides, with a free account you only have one Organization in Transifex.

**Comment by prschopf** [comment]
Why that in "U" in Transifex Ultrasonic team? https://s13.postimg.org/l61yra82v/ultrasonic.jpg

**Comment by ogarcia** [comment]
We close the issue. Online tool for translations is implemented. For future enhancements we should open more detailed Issues.
