### ISSUE TITLE
App won't shut down

### ISSUE THREAD

**Issue by daFreeMan** [ultrasonic/ultrasonic#103]
## Problem description

It is very difficult to get the app to shut down - it is almost always running in the notification bar.

### Steps to reproduce

Pull down the notification - there is an "x" in the corner of the notification. Touching that doesn't cause the app to exit. 
In the app main menu, at the bottom, there is an "Exit" option. Touching that closes the app interface, but leaves the icon in the notification bar. Pull-down on notification, touch the Ultrasonic notification, the interface pops up with "now playing" activated and the song paused where I last left it.

## System information

 * **Ultrasonic version**: 2.0.0 (this has been happening since I first installed it many months ago)
 * **Android version**: 7.0
 * **Device info**: Moto G5 plus

**Comment by ogarcia** [comment]
@daFreeMan Yes, is an old know issue that happens in certain circumstances.

There is a workaround that is, open the application switcher (pressing the square button in navigation bar), slide the application to the right or left to close it and then press the `x` in the notification. If don't work enter in the player, press play, press pause and then press `x`.

**Comment by daFreeMan** [comment]
thanks for the feedback. Unfortunately, I seem to hit the certain circumstances about 99% of the time. :(

**Comment by Tapchicoma** [comment]
@daFreeMan I've fixed the bug when clicking on *X* in notification does nothing, also can't reproduce now the *exit* menu issue.

Feel free to reopen it if it still happening for you.

Should be fixed in `2.4.0` version.

**Comment by ogarcia** [comment]
Version `2.4.0` published in [Releases](https://github.com/ultrasonic/ultrasonic/releases/tag/2.4.0) and in [beta channel](https://play.google.com/apps/testing/org.moire.ultrasonic) of Play Store.

**Comment by daFreeMan** [comment]
TYVM, guys. Appreciate the efforts!

**Comment by deusxanime** [comment]
Just trying out Ultrasonic and I still have this bug. Using an original Google Pixel with v2.5.0 downloaded from the Play Store. Notification is stuck in my status bar - can't X out, won't swipe away, and going into the app and selecting Exit from the menu doesn't kill it either. Also unchecked anything to do with Notifications in the app's settings. Tried to go into the Android app switcher and get rid of it and that didn't work. Finally had to go to Android settings and Force Stop it to kill it. Then I started up the app again and same thing all over again with stuck notification in status bar.

Once it is stuck it doesn't even seem to update with the current Now Playing song, it is just locked to whatever song was there when it first came up. But the controls (ff and rw) seem to at least still affect the player.

**Comment by Tapchicoma** [comment]
Yep, current behaviour that is prohibits swipe to exit action is frustrating, possibly this will addressed in one of next releases.

**Comment by deusxanime** [comment]
OK glad to know that it is still a known issue. Since this was closed, I wasn't sure if it was still being looked at. 

I was playing with it more over lunch and eventually the notification does seem to go away. Some combination of idle time and starting/stopping/opening/closing the app, eventually it clears out. 

Obviously the ideal state should be that X'ing out or swiping away the notification should clear it (assuming app closed and nothing actively playing), but at least good to know that it isn't stuck forever without a force stop of the app or restart of the phone.
