### ISSUE TITLE
API change? JSON?

### ISSUE THREAD

**Issue by davidgfnet** [ultrasonic/ultrasonic#109]
I see that the requests issues by Ultrasonic now seem to have "f=json", is that due to an upgrade to protocol 1.7.0?
I'm running davidgfnet/supersonic-cpp and of course it fails due to output being XML-only :(
My server is (in theory) version 1.4, I guess I need to upgrade it to 1.7.0 then? Or is it enough to downgrade it to 1.3 so the Ultrasonic doesn't try to use json but xml instead?
Thanks!

**Comment by Tapchicoma** [comment]
Hi, according to http://www.subsonic.org/pages/api.jsp `json` format should be supported since `1.4.0` version. 

Also App minimal supported version is `1.7.0`.

**Comment by wagnered** [comment]
Hello @ogarcia,

I am a developer on the Ampache/Ampache project.  There seems to be a problem with retrieving the list of albums from the Music->Artists menu item.  Only artists with multiple albums are successfully retrieved and displayed, The Ampache Subsonic API uses the PHP function  `json_encode`. 

json_encode doesn't seem to create a json array for one album entry. I think this is according to the json specs. I thought that this fact might be why Ultrasonic is showing the albums from only the artists with multiple albums.  

Kudo for an excellent Subsonic client.

**Comment by ogarcia** [comment]
Kudos for @Tapchicoma that is make the hard work. 😃 

@wagnered tomorrow morning look for your issue, seems a problem with `json_encode` in server, but I prefer make some tests to give you a well documented response.

**Comment by davidgfnet** [comment]
I agree the JSON documentation is pretty much non-existant. I feel very uncomfortable writing something based on an implementation. Could we get some specification so we can write a proper JSON writer? I have the feeling 99% of the subsonic clients/servers use XML and therefore JSON compatibility is going to be hard.

**Comment by Tapchicoma** [comment]
Indeed, there is examples on API page in `xml` format, but, from my experience, they are not complete as well.

@wagnered @davidgfnet you can check this folder for API expected responses examples in `json` format: https://github.com/ultrasonic/ultrasonic/tree/master/subsonic-api/src/integrationTest/resources.

**Comment by ogarcia** [comment]
@wagnered This is a sample of response with one artist with one album for `Music -> Artists` menu item.

```
{
  "subsonic-response": {
    "status": "ok",
    "version": "1.8.0",
    "indexes": {
      "lastModified": 1514502231000,
      "index": [
        {
          "name": "#",
          "artist": [
            {
              "id": "85a67219-b3fd-4d38-a8ac-4b3fd93207b1",
              "name": "3 Doors Down"
            }
          ]
        }
      ]
    }
  }
}
```

The response is easy to understand, step by step:

It have a header with two important variables, `version` that says what version of API is supported by server and `lastModified` the date of modification of the list.

```
{
  "subsonic-response": {
    "status": "ok",
    "version": "1.8.0",
    "indexes": {
      "lastModified": 1514502231000,
      "index": [
        {}
      ]
    }
  }
}
```

The `index` is an array of objects with letters from `A` to `Z` and including `#` for other artist that begins from number or symbols.

```
[
  {
    "name": "#",
    "artist": [
      {}
    ]
  },
  {
    "name": "A",
    "artist": [
      {}
    ]
  },
  {
    "name": "B",
    "artist": [
      {}
    ]
  },
  ..etc
  ..etc
]
```

And inside of every artist is a simple `id` (artist id), `name` (artist name) object.

```
[
  {
    "id": "42767ec5-52ca-4d14-a70c-63759e888f8e",
    "name": "ABBA"
  },
  {
    "id": "d99fc7d6-37f7-4d8f-89db-3fc431c46a07",
    "name": "Above & Beyond"
  }
]
```

**Comment by ogarcia** [comment]
In the other hand, when you ask for one artist from artist list, this is the request.
```
GET /rest/getMusicDirectory.view?id=42767ec5-52ca-4d14-a70c-63759e888f8e&u=USER&c=UltraSonic%2520for%2520Android&f=json&v=1.8.0&p=enc:PASS
```

And a sample of an artist with one album is.
```
{
 "subsonic-response": {
  "directory": {
   "child": [
    {
     "isDir": true,
     "album": "The Definitive Collection",
     "parent": "42767ec5-52ca-4d14-a70c-63759e888f8e",
     "created": "2017-07-01T13:51:15",
     "coverArt": "372ad726-6488-4537-9760-2d40dbb4fa05",
     "title": "The Definitive Collection",
     "artist": "ABBA",
     "id": "372ad726-6488-4537-9760-2d40dbb4fa05"
    }
   ],
   "id": "42767ec5-52ca-4d14-a70c-63759e888f8e",
   "parent": "1b2a156d-56da-4705-8f1c-fb68752cbb91",
   "name": "ABBA"
  },
  "status": "ok",
  "version": "1.8.0"
 }
}
```

Take note that the response in `child` is an array of objects but with only one object. Maybe in your code the `json_encode` function when the artist have only one album then the object is listed directly without array (like this):
```
{
  "subsonic-response": {
    "directory": {
      "child": {
        "isDir": true,
        "album": "The Definitive Collection",
        "parent": "42767ec5-52ca-4d14-a70c-63759e888f8e",
        "created": "2017-07-01T13:51:15",
        "coverArt": "372ad726-6488-4537-9760-2d40dbb4fa05",
        "title": "The Definitive Collection",
        "artist": "ABBA",
        "id": "372ad726-6488-4537-9760-2d40dbb4fa05"
      },
      "id": "42767ec5-52ca-4d14-a70c-63759e888f8e",
      "parent": "1b2a156d-56da-4705-8f1c-fb68752cbb91",
      "name": "ABBA"
    },
    "status": "ok",
    "version": "1.8.0"
  }
}
```

Take note that in the second sample, `child` have directly the object `{}` instead an array of objects `[{}]`. If your response is like the second one for artists with only one album then the client fails.

**Comment by davidgfnet** [comment]
I updated my repo and now my server supports XML and JSON. Had to change some minor things, like the Artists query, I was not using "index" and it did work both with Ultrasonic and Clementine. Now it works well with Ultrasonic using JSON. I'm not a huge fan of the subsonic protocol since you can clearly see that most stuff is legacy from previous versions of the protocol.

**Comment by ogarcia** [comment]
Related bugs cosed.
