### ISSUE TITLE
Question about Ultrasonic usage

### ISSUE THREAD

**Issue by prschopf** [ultrasonic/ultrasonic#114]
Its not a bug but a help request.

Im going to travel this weekend and I want to use Ultrasonic offline. I would like to download 2 or 3 entire albums to listen to them in this trip.

I know I may play them before this trip and they will be available offline. But I dont want to listen to them before because it will take several hours.

What can I do to solve that? Im using lastest version of Ultrasonic and Ampache Server

**Comment by Tapchicoma** [comment]
You can do it by entering into desired album, selecting all tracks and pressing pin icon - it will download all selected tracks.

**Comment by prschopf** [comment]
Perfect! Thank you!
