### ISSUE TITLE
Update app icon

### ISSUE THREAD

**Issue by Tapchicoma** [ultrasonic/ultrasonic#116]
I think it is time to update app icon to be more modern 😄 

Design style guides for launcher icon: https://material.io/guidelines/style/icons.html#icons-product-icons

One of possible variants is this ultrasonic Github organization icon.

**Comment by ogarcia** [comment]
+1, yes we can use the organization icon or open a help wanted to call to community to participate in a design of a new one.

@Tapchicoma what do you think?

**Comment by Tapchicoma** [comment]
Closed via #183
