### ISSUE TITLE
stray ">" in mp3 file list

### ISSUE THREAD

**Issue by davebiffuk** [ultrasonic/ultrasonic#117]
All my mp3s are showing up as "(320 kbps mp3 > )" (the 320 is just an example, the correct bitrate is shown). It looks like the stray ">" comes from ultrasonic/src/main/java/org/moire/ultrasonic/view/SongView.java and is intended to show that the file was transcoded. But these are just plain mp3 files; some I ripped myself (CD->wav->mp3) and some are purchased. I'm using supysonic, latest github master, with no transcoding configured.

## System information

 * **Ultrasonic version**: Ultrasonic 2.1.0 from the Play store.
 * **Android version**: Oreo (8.1)
 * **Device info**: Google Pixel 2

**Comment by Tapchicoma** [comment]
Fix should be available in upcoming release (next after `2.2.1` version).
