### ISSUE TITLE
error happens when use multi byte string

### ISSUE THREAD

**Issue by ghost** [ultrasonic/ultrasonic#118]
## Problem description

Sorry for my bad english. I use ultrasonic for my Ampache server. There are many musics, artists and albums named in japanese because I'm japanese.

But error happens when I try to open artists and albums named in japanese.
```
A network error occurred. Please check the server address or try again later.
```
I can open them named with english.

I can't search with japanese but I can search with english.

### Steps to reproduce

I think this error occurres when send requests included multi byte string to server.

## System information

 * **Ultrasonic version**: *2.1.0*
 * **Android version**: *5.1.1*
 * **Device info**: *Fujitsu Arrows RM02*

**Comment by Tapchicoma** [comment]
I have one artist with Japanese name and it opens fine, though I am using Airsonic server. It may be a bug in Ampache.

I will try to reproduce it.

**Comment by ogarcia** [comment]
@thoth-42 I make several tests with Supysonic, Airsonic and Ampache and cannot reproduce the issue. I have a lot of music with _extrange chars_ as `áéíóú` or `ñ` or `ü` that works equal as japanese characters and can open it or search for it correctly, even with Ampache.

Are you sure that you have tagged correctly with UTF-8 your music? Can you send us some example file that not works?

**Comment by ghost** [comment]
Thank you for your replying.

 First, I checked error logs on my server after UltraSonic got errors. But there was no error but there were access logs like normal.

 Next, I tried to access the url written in the logs.

Opened the album named in japanese (文化).

URL: `https://[address]/rest/getMusicDirectory.view?id=200000022&u=[username]&c=UltraSonic%2520for%2520Android&f=json&v=1.11.0&p=enc:[encoded password]`  
Response:
```
{
    "subsonic-response": {
        "type": "ampache",
        "version": "1.11.0",
        "status": "ok",
        "directory": {
            "id": 200000022,
            "name": "\u6587\u5316",
            "parent": 100000030,
            "child": {
                "id": 300000066,
                "parent": 200000022,
                "title": "\u30c9\u30e9\u30de\u30c4\u30eb\u30ae\u30fc",
                "isDir": false,
                "isVideo": false,
                "type": "music",
                "albumId": 200000022,
                "album": "\u6587\u5316",
                "artistId": 100000030,
                "artist": "Eve niconico",
                "coverArt": 200000022,
                "duration": 245,
                "bitRate": 192,
                "genre": "Rock",
                "size": 5899630,
                "suffix": "mp3",
                "contentType": "audio/mpeg",
                "path": "Eve/\u6587\u5316/\u30c9\u30e9\u30de\u30c4\u30eb\u30ae\u30fc.mp3"
            }
        }
    }
}
```

Searched with japanese keyword (ほげ).

URL: `https://[address]/rest/search2.view?query=%E3%81%BB%E3%81%92&artistCount=10&albumCount=20&songCount=25&u=[username]&c=UltraSonic%2520for%2520Android&f=json&v=1.11.0&p=enc:[encoded password]`  
Response:
```
{
    "subsonic-response": {
        "type": "ampache",
        "version": "1.11.0",
        "status": "ok",
        "searchResult2": []
    }
}
```

 Ampache returns results normally. But UltraSonic gets error. (I can listen songs named in japanese.)

 I set artist, genre and other information on browser. So I think mp3-tag is not cause.

**Comment by ogarcia** [comment]
Ok. I see the problem.

In your example you are searching for `ほげ` that produces an empty result `"searchResult2": []`, but this response not is correct, the empty response must be `"searchResult2": {}`.

For example, testing with Supysonic:
```
{
 "subsonic-response": {
  "status": "ok",
  "searchResult2": {},
  "version": "1.8.0"
 }
}
```

The bug is in ampache not in ultrasonic. Please file a new bug in https://github.com/ampache/ampache/issues and referrer to this bug.

**Comment by ghost** [comment]
Thank you for your replying and sorry for my noise.

 I've just understood why I can't open albums or artists named in japanese. All of them have only one music. So children property became object type in opening albums.

 I'll open new issue in Ampache repository soon.   Thank you.

PS: There is already the same issue. ampache/ampache#1651

**Comment by ogarcia** [comment]
The problem not is that the names are in japanese, is the bad response format of ampache. In your response you have `"child": {}` that is incorrect, the correct format is `"child": [{}]` (the result inside of array).

There is a bug related about this in ampache: https://github.com/ampache/ampache/issues/1651
