### ISSUE TITLE
Video playback issue

### ISSUE THREAD

**Issue by retro-78** [ultrasonic/ultrasonic#119]
## Problem description

I cannot navigate into a video played from ultrasonic with VLC (the progression bar is stuck a the beginning)

### Steps to reproduce

read a video content from ultrasonic

## System informations
 * **Ultrasonic version**: 2.0.0
 * **Android version**: 7.1.2
 * **Device info**: Xiaomi Redmi 4x

**Comment by Tapchicoma** [comment]
Hm, I successfully open the video in VLC.

What Subsonic API implementation are you using?
What is the video file format?

**Comment by retro-78** [comment]
Hi

I am using an airsonic server which is normaly compliant with the version 1.15 of the API.

The video is an avi file. I am able to play the file too but the progression bar doesn't work properly (cursor stay at the left) and the duration of the video ( at the bottom right corner) stay at 00:00.

What server are you running on your side ?

Thanks

**Comment by Tapchicoma** [comment]
Airsonic as well. And yes, I also see such problem, but Ultrasonic just passes to VLC video stream url, so I suppose it is the problem in interaction between VLC - Airsonic (like some response headers are missing, like `Content-Length`)

**Comment by retro-78** [comment]
OK so it's a bug which coming from the airsonic server side. 

This problem is annoying... 

I am gonna create an issue on the airsonic repo

Thanks
