### ISSUE TITLE
Support "all songs" in offline mode

### ISSUE THREAD

**Issue by captn3m0** [ultrasonic/ultrasonic#120]
## Problem description

I recently migrated from Google Play Music to Airsonic+Ultrasonic, and I miss the "Songs" view. While Songs->Random and Songs->Starred are possible while online, there is no similar view for Offline Songs.

When offline, I'd like to get a playlist of everything I have cached and listen to it. A simple "All Artists" at the top of Media Library in offline view might work

### Steps to reproduce

- Switch to offline.
- Try playing all offline songs across all artists.

## System information

 * **Ultrasonic version**: *2.1.0*
 * **Android version**: *7.1.1*
 * **Device info**: *Moto Z Play*

**Comment by ogarcia** [comment]
See #718
