### ISSUE TITLE
Unable to connect (network error occured) since last update

### ISSUE THREAD

**Issue by draccas** [ultrasonic/ultrasonic#128]
Hello,

I'm using Ultrasonic with an Airsonic server.
Everything worked well, but since last update I can't connect anymore.
I have the following error message when using "Test Connection":

_Connection failure. A network error occured. Please check the server address or try again later_

And same when trying to get arsits:

_A network error occured. Please check the server address or try again later._

I watch the log in my server but nothing: Ultrasonic seems no connect.
I also try to go on server URL from my Android and works good.

Did you make a change that can explain that?
Thanks in advance.

**Comment by ogarcia** [comment]
@draccas 

Please can you provide more info?

## System information

 * **Ultrasonic version**: *version of the app*
 * **Android version**: *Version of Android OS on the device*
 * **Device info**: *Device manufacturer, model*

Are you using HTTPS with self-signed certificate? In this case you must select the _Allow self-signed HTTPS certificate_ option.

Other cause is that you must write protocol in the URL, if your server is example.com you must set it as http://example.com

**Comment by paddatrapper** [comment]
Chiming in here because I have the same issue, also using airsonic.

## System information

    Ultrasonic version: 2.1.0
    Android version: 7.0
    Device info: Samsung J5 Pro (SM-J530F)

I am using a LetsEncrypt certificate and other clients (both web-browsers and the subsonic android app) connect with no issues. I have the https protocol in the URL.

**Comment by Tapchicoma** [comment]
Hm, I am also using Airsonic with Let's encrypt certificate and everything works ok 🤔

**Comment by Tapchicoma** [comment]
What Airsonic version are you using?

**Comment by paddatrapper** [comment]
10.1.1-RELEASE on Debian stable behind a nginx proxy (LXC containers if that makes a difference)

**Comment by Tapchicoma** [comment]
Ok, almost same for me - `10.1.1-RELEASE – December 16, 2017` using docker image behind nginx proxy.

Seems app need a way to collect request-response logs and save it locally, so it can be attached to issue.

**Comment by draccas** [comment]
Thanks for your response.

> Are you using HTTPS with self-signed certificate? In this case you must select the Allow self-signed HTTPS certificate option.

Sorry, I can't find this option. Where is it?

I do not use Let's encrypt. My certificate is self signed.

Ultrasonic version: 2.0.0 (from F-Droid)
Android version: 7.0.1 (Lineage OS)
Device info: OnePlus 3
Airsonic version: 10.1.1 + nginx proxy from Airsonic documentation.

This is an awesome app. Thanks for your help.

**Comment by ogarcia** [comment]
> Sorry, I can't find this option. Where is it?

With latest version (2.1.0). Into server settings, between enabled and jukebox options.

@paddatrapper If you check the _Allow self-signed HTTPS certificate_ persists the issue?

**Comment by draccas** [comment]
Unfortunately the version is not up to date in F-Droid and I have not the Play Store on my phone.
Can you update you app in this repository please? 

I thinks this probably fix the bug, because as I say I have no trace in Airsonic log when trying to connect with Ultrasonic.

**Comment by paddatrapper** [comment]
> @paddatrapper If you check the Allow self-signed HTTPS certificate persists the issue?

Uninstalling and re-installing the app fixed the issue for me

**Comment by Tapchicoma** [comment]
@paddatrapper you maybe affected by your issue: https://github.com/airsonic/airsonic/issues/676. I've just have same on test env.

#121 - in next version app will show better errors messages

**Comment by ogarcia** [comment]
@draccas if you are using the FDroid then download [version 1.8](https://f-droid.org/repo/org.moire.ultrasonic_58.apk), because they have problems with the build servers and the version 2.1.0 is not available.

There is an issue open for this cause in https://gitlab.com/fdroid/fdroiddata/issues/1053

**Comment by draccas** [comment]
@ogarcia Thanks it works on 1.8.
Hope F-Droid will resolve their problems.

**Comment by ogarcia** [comment]
@draccas we update client with several enhancements but unfortunately F-Droid people still have issues with they build servers. I recommend you download our [latest apk build 2.2.0 from our repo](https://github.com/ultrasonic/ultrasonic/releases/download/2.2.0/ultrasonic-2.2.0.apk) and tell us if work as expected. Take note that the certificate that signs the akp is not the same because F-Droid use his own certificate.

**Comment by ogarcia** [comment]
New issue open in F-Droid because no new builds https://gitlab.com/fdroid/fdroiddata/issues/1107

**Comment by Tapchicoma** [comment]
We removed versioning plugin that causes the problems to build of F-Droid, but it is not yet merged into `master`. F-Droid should build next release.

**Comment by Tapchicoma** [comment]
@draccas `2.1.0` is available on F-Droid. Can you check again?

**Comment by ogarcia** [comment]
Latest release is now in F-Droid, we can close this issue.
