### ISSUE TITLE
Add a way to collect logs

### ISSUE THREAD

**Issue by Tapchicoma** [ultrasonic/ultrasonic#130]
## Problem description

Add a way in the app to collect logs and save the locally on the device. This will allow app users to attach more helpful information to the issues (like in the #128 or #129).

## Additional notes

This may depends on adding better logging solution story.

**Comment by nitehu** [comment]
Its not the first time I encounter some issues on the go, and when I plug my phone to my computer, I can't reproduce it. Not to mention issue reports by users, where it would be life saver if they could attach the logs. Saving the logcat logs on the phone needs root access which is not an option for many.

I've checked some logging libraries for Android, but I think Ultrasonic needs something very simple:
- Logging turned on and off from the settings
- While turned on, redirect "Log" functions (and unhandled exceptions) to a file in the app dir
- Rotate the files when they reach a predefined size
- Some user convenience functions, like showing an alert at Ultrasonic startup if the logs reached a number, with options to delete them, turn off logging, etc.

**Comment by Tapchicoma** [comment]
I would propose to use Timber library with a custom implementation of `Timber.Tree`. Implementation could be controlled whether it will log into the file or not, plus additionally log into logcat for debug builds.

Imho logging into the file should be disabled by default.
