### ISSUE TITLE
Sync issue - music must be re-synced but still on phone and playlist shows files present

### ISSUE THREAD

**Issue by irie27** [ultrasonic/ultrasonic#133]
## Problem description

I have a Subsonic server running 6.1.1 on Linux Mint 18.1. I have a external IP address and LAN address for the same Subsonic server.  When I sync using the LAN IP, sometimes the music is showing as no longer synced.  The playlist still shows all the songs I synced, the files are still on the phone (viewing with Root Explorer), but Ultrasonic shows that the files must be re-synced and once I get back on WIFI, the synching process begins.

### Steps to reproduce

Good question since it doesn't happen all the time.

## System information

 * **Ultrasonic version**: 2.1
 * **Android version**: 5.1
 * **Device info**: HTC M7

**Comment by Tapchicoma** [comment]
Can you describe what do you do to mark songs/playlists that need to be synced? (pin action?) And how you see that they no longer synced, needs to be resynced?

**Comment by irie27** [comment]
I mark the songs in 1 of 2 ways.
1. From within Ultrasonic Main Menu, I click on Albums/Recently Added.
2. From within Ultrasonic Main Menu, I click on Songs/Starred.

The syncing begins without a problem.  Everything will be alright, but every once in awhile (sometimes after exiting the app, sometimes out of the blue), I'll continue playing the songs in the playlist and then the music stops.  I look at the playlist and see the playlist is still full, but the down arrow showing each file that was synced is no longer there.  

I verify the files are there by using Root Explorer and browsing to the file storage location.

**Comment by Tapchicoma** [comment]
Possible reason: cache cleaner job kicks in and clears some of your current playlist files. Generally app should just not care about it and redownload the song.

This behaviour may be improved in #98 issue.

**Comment by irie27** [comment]
One scenario is it seems to happen whenever the phone reboots suddenly. Its happen a couple of times already with the same behavior.  It also happens out of the blue but I'm unable to figure out why.  I just checked the playlist now and the files have to be resynced/downloaded from the server even-though it's the same playlist that has been on there for a week.

![screenshot_2018-01-18-06-39-19](https://user-images.githubusercontent.com/1542442/35199145-232fe986-fec8-11e7-9a0b-9d721936fcbb.png)

As you can see by the following picture, the files are still present.

![screenshot_2018-01-21-16-32-22](https://user-images.githubusercontent.com/1542442/35199190-d5315a2a-fec8-11e7-90f5-645143a94307.png)

**Comment by irie27** [comment]
Just an update on the issue, last night I updated to version 2.2.1 and when I fully exited the app using the menu, I started the app again and a resync was needed, but this time only 10 files didn't need to be synced.

**Comment by irie27** [comment]
Any updates to this issue?

**Comment by Tapchicoma** [comment]
Nope, this bug is not easy fix and app has to change a lot of code to address this.

**Comment by irie27** [comment]
Ok, is it possible to add something along the lines of "play local files" since the files are already on the phone, Ultrasonic just can't detect them without a resync?

**Comment by Tapchicoma** [comment]
you want to have some kind of indication that music file is not available?

**Comment by irie27** [comment]
No.  Possibly an option to browse to where the music files are stored on the phone and play them from there.
