### ISSUE TITLE
Wrong cover art

### ISSUE THREAD

**Issue by davidgfnet** [ultrasonic/ultrasonic#134]
## Problem description

The App uses a wrong cover art when showing the album song list. The covers are ok whenever listing some author's album or the full album list.

### Steps to reproduce

With the app freshly installed (wipe data) browse for a song and play it.
Clear the playlist and go back to Artists then Albums and open one album. The album cover art will be from the song you just played instead of the correct one.

## System information

Using the latest ultrasonic from play store.
I use my own server to serve this content. I noticed that whenever I browse to an Album song list, it will usually query the album art using a bigger size (compared to the small album list). After the song is played the albums cover art will always be wrong and the same as the played song.

## Additional notes

After debugging a bit I noticed that browsing doesn't get any cover art dropped to disk as a JPEG image. Only when I play the first song I will get some file dropped to the local disk cache. In my case I get:

/storage/emulated/0/Android/data/org.moire.ultrasonic/artwork/101a46b761af499a52c53b6c1368afac.jpeg

Which comes from:

hex(md5(/storage/emulated/0/Android/data/org.moire.ultrasonic/music/null)) = 101a46b761af499a52c53b6c1368afac

Which means that there's some bug that makes all songs to end up in "music/null/song.mp3" instead of "album/song.mp3". That means there is always (obviously) a cache hit for the cover art.

I'm unsure who's to blame for this bug, whether it's a thing that my server produces somehow or it's a client bug. I will check a bit more but I'll probably need a bit of help since just reading the code might not be enough and I'm not planning to build the apk to debug.

**Comment by Tapchicoma** [comment]
Nice description 👍 

I've tried to reproduce but without a success. What server implementation are you using?

**Comment by davidgfnet** [comment]
Check my repo supersonic-cpp, it's my own.
So, do you see how could it be that the path ends up containing the string "null"? Cause I don't! There's explicit checks for ==/!= null in most places to prevent that.

**Comment by davidgfnet** [comment]
How can I help you with this?

**Comment by Tapchicoma** [comment]
I am currently trying to implement new caching system that is needed for Api 23. It may help. Also app should use better approach to download and display images, but this a separate task.

**Comment by davidgfnet** [comment]
I think the bug here is that you use "path" field returned by the server, is that correct? I think this is a "recent" change to Ultrasonic, it used to be the case that ultrasonic would create its own directory structure. That's also the same issue with offline content not working correctly, for some reason paths are just "null" (my server does not provide "path" field), and also you filter by extension, and for some reason the extension is "". That results in files like "foo/bar." (no extension after "."). In the case of having no path it results in "null/." which is already an existing path :(
If you want my opinion here: do not ever use the path that server returns, it could easily be invalid (too long, since all filesystems have limits, some forbidden character since you don't check which chars are ok and which are not in your filesystem (also remember that the FS could be FAT32 or EXT3/4 depending on device!)) use instead a path of your own creation, perhaps incrementing numbers for songs (1.mp3 ...) and have the song info in your database to map the files, or just use ID3 if you really want (might return different values than subsonic server though).

**Comment by ogarcia** [comment]
Checked and fixed in 2.2.2
