### ISSUE TITLE
Better feedback to user on certificate error

### ISSUE THREAD

**Issue by ogarcia** [ultrasonic/ultrasonic#135]
At this moment, when an user have a certificate problem (is using a self-signed certificate or certificate is invalid), they receive the generic error `A network error ocurred. Please check the server address or try again.` that may be confusing.

I think that is better give a more detailed error in this case. And I see two different situations.

1. If the user is trying to connect using https with a _no valid / unknown_ certificate and have not checked the _self-signed certificate_ option give an error like `You are using an unknown or self-signed certificate. If this is your intention, please check the allow self-signed HTTPS certificate option.`
2. If the user have an expired certificate (that is invalid in any case), give something like `Your HTTPS certificate is expired and cannot be used, please renew your certificate to connect with your server.`

With this I think that we can avoid issues like #128 or #129

**Comment by Tapchicoma** [comment]
There is no straightforward way to detect exact SSL problem. I've added more specific error message to certificate problem or general SSL error.
