### ISSUE TITLE
Second instance / second song starts playing

### ISSUE THREAD

**Issue by mgoldeyy** [ultrasonic/ultrasonic#153]
## Problem description

The next track in the playlist starts playing in a "headless" instance of Ultrasonic while the current track continues to play in the running instance.  Both tracks play simultaneously.  Pausing the running instance or terminating the application stops the current track from playing, but because there is no visible instance of Ultrasonic playing the second track, the second track cannot be stopped without rebooting the playback device.

### Steps to reproduce

Add tracks to a playlist and see if it happens.  Unfortunately, there is no predictable pattern that I can see.  
I have been using Ultrasonic for a few years and this used to happen occasionally, but I chalked it up to random glitches, and it's hard to debug something while walking or driving.  But today it happened ibn my living room, twice in 10 minutes despite a reboot in between events.  

In each case, the content had been fully downloaded from my Subsonic server and was saved on my phone.  

As best I can tell, this only happens when longer tracks are selected.  Today the problem occurred after 9 minutes of a 17 minute track.  First, playback stops for a moment.  Toggling play/pause has no effect.  Moving the playback slider has no effect.  It's as if Ultrasonic has frozen, and very similar to what happens if playback reaches the end of the partially-downloaded track:  playback stops dead and the playback controls won't provide full control.

After a moment, playback resumes.   When it does, the second track also starts playing.  Or, if I have been adjusting the playback controls an fiddling around, the second track seems to start once I am able to start the first track again.  Either way, it seems like Ultrasonic freezes while it somehow loads a second track up and starts playing it.  Then it proceeds as if nothing happened.

Once I hear that two tracks are playing, I can pause or even stop the track that's playing in the visible Ultrasonic window.  The second track continues, however.  There is no obvious way to interact with it.  Terminating Ultrasonic does not stop the second track from playing.  Restarting Ultrasonic does not force the second track into the visible instance, either.  It is really as if a second, headless instance is running and playing the next track in the playlist.  

Anyway, this has happened enough times, and across enough phones and versions of Android, that I decided it was time to mention it.  

## System information

 * **Ultrasonic version**: 2.2.1 but also 2.2.0 and earlier versions
 * **Android version**:  Nougat, but also Marshmallow and earlier versions
 * **Device info**: Samsung S6 edge, but also on an S5 and an S4.

**Comment by evan-goode** [comment]
I've been having this issue since I started using Ultrasonic. I have to "force stop" it to get the second track to stop.

I'm running LineageOS 15.1 on a Oneplus 5T. I can dig a little deeper, perhaps post a logcat if it would be helpful.

**Comment by 4oo4** [comment]
I think I managed to capture this happening in a logcat, will post that in gitter. This also happens to me on occasion, also using LOS 15.1 on OnePlus 5T. From experience, it seems to happen when getting towards the end of a longer (10+ minute) song.

**Comment by mgoldeyy** [comment]
This happened to me again a week ago while driving.  Also a long song.  Freeze, then both instances started playing at the same time.  

Samsung S6 (same phone as before), Android 7.0, Ultrasonic 2.5

**Comment by 4oo4** [comment]
Any update on this? This is a super annoying bug. I'm taking a stab in the dark as to what could be causing this, could it be related to `MenuDrawer`? I see a default duration of 600 for a menu animation, could it be when that duration is reached during playback, that's what triggers the behavior?

https://github.com/ultrasonic/ultrasonic/blob/7370fb73a30957adfb641d1757acbcd3310abe27/core/menudrawer/src/main/java/net/simonvt/menudrawer/MenuDrawer.java#L173-L176

https://github.com/ultrasonic/ultrasonic/blob/7370fb73a30957adfb641d1757acbcd3310abe27/core/menudrawer/src/main/java/net/simonvt/menudrawer/DraggableDrawer.java#L342-L373

**Comment by 4oo4** [comment]
That doesn't seem to be it, but whatever is causing it, it's calling `writeObject`.

```
10-07 20:09:14.823 I/FileUtil( 8008): Serialized object to /data/user/0/org.moire.ultrasonic/cache/downloadstate.ser
```

https://github.com/ultrasonic/ultrasonic/blob/7f36c74060cfce653e66a4c3515569f17dadf284/ultrasonic/src/main/java/org/moire/ultrasonic/util/FileUtil.java#L538-L559

**Comment by 4oo4** [comment]
Any updates on this? I just noticed that with Android Q (stock Pixel 3 ROM) that it now will stop the first song and the second "headless" one takes over, whereas with Android O and P it would play them both simultaneously (that was OnePlus 5T on LineageOS though).

**EDIT:** I wonder if 2.6.2 may have fixed this? Since updating I haven't been able to reproduce this. I'll do some more testing.
