### ISSUE TITLE
Server settings mockups

### ISSUE THREAD

**Issue by ogarcia** [ultrasonic/ultrasonic#156]
This is only examples that we may use.

Personally i love the Yatse concept:

![Server List](https://yatse.tv/Images/YatseV7/Configuring/Hosts/01.png)
1: Servers list
2: Add new server button

The dropdown menu may be optional, but is a great idea for move server on list
![Dropdown menu](https://yatse.tv/Images/YatseV7/Configuring/Hosts/02.png)
The options 3 and 4 not apply in our case.

Add server window only ask for basic configuration:
![Add Server](https://yatse.tv/Images/YatseV7/Configuring/Hosts/05.png)

And sends you to *Edit Server* with two tabs
![Edit Server Basic](https://yatse.tv/Images/YatseV7/Configuring/Hosts/06.png)
![Edit Server Advanced](https://yatse.tv/Images/YatseV7/Configuring/Hosts/08.png)

In this case most of options of advanced view don't apply in Ultrasonic, but is a idea.

The basic settings can be equal:
- Name of connection
- Server Address
- Server port -> This setting may be in advanced under a option named _Use non standard port_?
- Usename
- Password
- Server enabled or disabled

The advanced settings can be:
- LDAP Support
- Default Jukebox
- Connection type (http or https) if user select https then show the _self-signed_ option.
- Future options...

As I say, this is only a possible view of server settings and it may not match the final version.

**Comment by chrisacameron** [comment]
Include a "Test Connection" button or do so on save to validate settings
