### ISSUE TITLE
Offline mode not working

### ISSUE THREAD

**Issue by davidgfnet** [ultrasonic/ultrasonic#160]
Offline mode does not work. When I work to Media Library i get a single row, text is "null". Taping on it shows a " No media found".

This used to work and I did make intensive use of it. I think, since I assume it works for other people, that the client works poorly with my custom server. Even if that is the case I suspect the client expects certain conditions to be met and blindly trusts the server or something. Othetwise how could the server break the client?

Im exited that the project is getting some attention, but breaking stuff is no good either :(

I guess I can help debugging this somehow.

**Comment by ogarcia** [comment]
@davidgfnet can you add a README in [your project](https://github.com/davidgfnet/supersonic-cpp) explaining the steps to compile and use the server? So I could run an instance and make some debug :-)

**Comment by ogarcia** [comment]
Fixed in 2.2.2
