### ISSUE TITLE
New music is being saved with .complete filetype

### ISSUE THREAD

**Issue by sprnza** [ultrasonic/ultrasonic#167]
## Problem description

Music that's being downloaded is saved with .complete filetype so in offline mode Ultrasonic is not able to access it.

 * **Ultrasonic version**: 2.1.0
 * **Android version**: 4.4.4
 * **Device info**: Meizu MX2

**Comment by ogarcia** [comment]
You are using old version of Ultrasonic. Please download latest version fom [Releases](https://github.com/ultrasonic/ultrasonic/releases).

**Comment by sprnza** [comment]
@ogarcia thanks! Will f-droid version be updated anytime soon? Or it's better to get it installed from Google Play?

**Comment by ogarcia** [comment]
F-Droid have update problems. You can see more info here https://gitlab.com/fdroid/fdroiddata/issues/1107

You can wait for fdroid fix, update by hand from our releases or use Google Play version that is updated.

**Comment by sprnza** [comment]
@ogarcia Coll! Thanks! And thanks for the app! It's great!

**Comment by sprnza** [comment]
2.2.2 behaves the same. It's not `.complete` but `.complete.` with a trailing dot.
Edit: can't find an option to reopen the issue.

**Comment by ogarcia** [comment]
That is very extrange behavior. What server and version are you using? Your music is in mp3 or in other format? Are you making transcoding in server?

**Comment by sprnza** [comment]
I'm using Airsonic 10.1.1, all music is in mp3 so no any extra transcoding is being used. I'll check how it works in Dsub.

**Comment by sprnza** [comment]
in Dsub files are being named like `*.complete.mp3`. So `mp3` is not missing.

**Comment by ogarcia** [comment]
I'm trying with latest version 2.2.2 and Airsonic 10.1.1 an cannot reproduce the bug. All songs are download as `*.complete.mp3`.

Do you uninstall the previous version and do a clean install? (And delete or rename the org.moire.ultrasonic folder).

**Comment by sprnza** [comment]
Well, I've done what you suggested and now everything's just fine. Thank you.
