### ISSUE TITLE
Add code coverage

### ISSUE THREAD

**Issue by Tapchicoma** [ultrasonic/ultrasonic#17]
Should add code coverage metric to see changes in time.

As now main goal is to rewrite to kotlin - we should enable code coverage only for kotlin code.

Optional: badge in README.md

**Comment by Tapchicoma** [comment]
I've added code coverage report, but it would be nice also to see difference on the PR and see overall code coverage badge.

I've found two services that are free for open source projects:
* [https://codecov.io/](https://codecov.io/)
* [https://coveralls.io/](https://coveralls.io/)

@ogarcia can you add this project to one of them? Personally first one looks better.

**Comment by ogarcia** [comment]
@Tapchicoma Done!

I added the first one (https://codecov.io). As you say, it looks better.
