### ISSUE TITLE
File download doesn't seem to work

### ISSUE THREAD

**Issue by daFreeMan** [ultrasonic/ultrasonic#170]
## Problem description

I have my home server behind LetsEncrypt & NGINX, so when not at home I have to access it via VPN. Therefore, I want to download a selection of music to my phone so I can listen while running. I'm running Libresonic (v6.2 – May 2, 2017) on the server. When I select a playlist of songs to download, I can't get Ultrasonic to download them to the phone.

### Steps to reproduce

In UltraSonic Main, ensure that my "Home" server is selected
Select a variety of songs into a playlist.
I saved the list so I could switch between a couple.
From the Navigation slideout, I select playlists, then my desired playlist.
It shows 104 songs & 11 hours of music
I hit the "4-squares" button at the bottom center & get the "104 tracks selected" toast
I click the download icon.
I get the "104 songs selected to be downloaded" toast.
Nothing downloads.
I don't see the downloading graphic on any of the tracks.

If I hit play on the playlist, the triangle "play" icon changes to the 2-bar "pause" icon, but nothing plays. 
When I turn up the volume, I get a pop-up that says "Remote volume" and a thermometer bar.

## System information

 * **Ultrasonic version**: 2.2.2
 * **Android version**: 7.0
 * **Device info**: Moto G5Plus

## Additional notes

I do have some songs downloaded to the phone by Ultrasonic, so it has worked, but I don't recall when they actually were downloaded - it may have been on an earlier version of client.

Looking at the server itself, I see this in the config for the player:
External Player with Playlist - selected
Max Bitrate - no limit
all check boxes checked.

I just noticed - After switching to Offline mode then going to playlists, I have an "Offline:" version of one playlist and a "home:" version of it, too. The other one, which I'm trying to get pre-downloaded so I can use it offline only shows a "home:" version of it. This may well be more of a clueless user support issue than a bug report...

**Comment by ogarcia** [comment]
@daFreeMan Please, delete (or rename) the cache folder (by default in `Android/data/org.moire.ultrasonic`) and try again.

**Comment by daFreeMan** [comment]
Thanks for getting back to me so quickly, @ogarcia.

I renamed `Android/data/org.moire.ultrasonic` to `Android/data/org.moire.ultrasonic.old`. 
I launched Ultrasonic again, selected my playlist (all while at home and with the "Home" server selected), selected all songs (now down to 90 tracks instead of the previous 104), hit download, and again nothing. 

No indication that tracks were beginning to download at all. Now, about 2 hours later and at the office, I have no tracks to play when I've selected the `Offline` server.

Anything else to try? Are there log files I can post?

**Comment by ogarcia** [comment]
@daFreeMan I cannot reproduce your behavior with the same setup. If you select only one song and press download it works?

You may see the download icon in the list as this screenshot.
![downloaded_songs](https://user-images.githubusercontent.com/572924/36597909-e86bfcb6-18aa-11e8-8a07-9c6de6e33b5f.png)

**Comment by daFreeMan** [comment]
I tried selecting a single song (the first one in this screen shot) then hit the download icon:
![screenshot_20180223-092208](https://user-images.githubusercontent.com/11889733/36598802-6991236e-187b-11e8-94dd-3767dac7654f.png)

And this is what I see a few moments later:
![screenshot_20180223-092213](https://user-images.githubusercontent.com/11889733/36598865-8b194ff2-187b-11e8-81e1-65b4ada3a092.png)

Now, a couple of minutes later (as I got screen shots, emailed them to myself, typed this up...) it's still not showing the download icon next to the track I selected.

I'm at the office and connected to the home server via VPN, so this should be the same net result I'd get if I was sitting at home.

(Wow those images are HUGE! Sorry...)

**Comment by daFreeMan** [comment]
@Tapchicoma  - happy to provide more info if you'll tell me what you need.

**Comment by ogarcia** [comment]
@daFreeMan if you play any song of the list you see the download icon?

**Comment by daFreeMan** [comment]
Nope. Sitting at home on the WiFi, "Home" server selected. I pulled up the playlist, selected the first song and hit play. This is what I see:
![screenshot_20180224-120351 smaller](https://user-images.githubusercontent.com/11889733/36632972-764c0b4c-195b-11e8-9152-8674c512201a.png)

If I change volume:
![screenshot_20180224-120331 smaller](https://user-images.githubusercontent.com/11889733/36632977-7fdccf16-195b-11e8-898a-5414b430b4b1.png)

Note that it shows that it's playing (the pause icon is visible, instead of the play icon), and that it says it's changing the Remote Volume. 

Do I somehow have my player set up incorrectly in Libresonic?
![image](https://user-images.githubusercontent.com/11889733/36632999-f3d5231e-195b-11e8-9369-b0b6df028852.png)

(Tried resizing those images in PS so they wouldn't be so big. Didn't work...)

**Comment by ogarcia** [comment]
@daFreeMan seems a server misconfiguration, but please, enter in our [gitter channel](https://gitter.im/ultrasonic/ultrasonic) and chat me privately to give me an user / password for make tests.

**Comment by ogarcia** [comment]
@daFreeMan any new? Can you enter in our [gitter channel](https://gitter.im/ultrasonic/ultrasonic)?

**Comment by ogarcia** [comment]
No more info provided by issuer. I go to close issue and if issuer gives us new info I will reopen it.

**Comment by daFreeMan** [comment]
Sorry, @ogarcia, I really appreciate the offer to help - I've been hit with a variety of other issues that have pushed this to a lower priority. I'll get back with you later this evening (US EDT - GMT-5) time and join you in gitter.
