### ISSUE TITLE
Server version sometimes may not be updated

### ISSUE THREAD

**Issue by Tapchicoma** [ultrasonic/ultrasonic#174]
## Problem description

Supysonic sends `"version"` value in json response at the end. As client currently peeks 100 first bytes of response for version information, this may lead to error state if other response data takes more then 100 bytes.

## System information

 * **Ultrasonic version**: *2.2.2*

**Comment by Tapchicoma** [comment]
@ogarcia I've improved situation, but it is not 100% fix. So I will keep this issue open.

**Comment by ogarcia** [comment]
@Tapchicoma Ok. At least it works :smile:
