### ISSUE TITLE
Delimiter-Separated Multiple Genre Support

### ISSUE THREAD

**Issue by innerspaceboy** [ultrasonic/ultrasonic#186]
Ultrasonic's genre browse feature is a wonderful enhancement over Subsonic but it would be infinitely more useful if it supported multi-genre tags with delimiter-separated values.

This is unfortunately the result without such support::

![Screenshot](https://i.imgur.com/vmXlK8zm.png)

As different users employ different delimiters, Ultrasonic could add a field in the user configuration where users can specify a tag separator like "," or "|" or ";" so that Ultrasonic can recognize multiple genres from the song's tags.

**Comment by ogarcia** [comment]
The point is that the genre in a song must be unique. An album can have multiple genres but a song not. This feature has not much sense. If you set genres in your songs one by one you cannot need this feature.

**Comment by innerspaceboy** [comment]
Thank you so much for the quick reply.

Multi-genre tagging with delimiters has been supported ever since ID3v2. While not adopted by all players, users with substantial libraries (50,000 - 1,000,000+ tracks) have migrated to players that do support this feature out of necessity.

Multi-genre tagging is presently supported by:

- Foobar2K
- Quod Libet
- Clementine
- MediaMonkey
- Lollipop
- MusicBee
- PowerAmp
- Slimserver
- Windows Media Player
- and gMusicBrower
- with pending support for GoneMAD
 
Most of the applications above use ";" as the default separator. This is an essential function of all large library music managers. 

Ultrasonic excels in being a slick and scalable interface specifically for users with extensive libraries and the feature is highly-sought after by discerning users.

Please reconsider implementing this essential enhancement.

**Comment by Tapchicoma** [comment]
Personally I think it is a valid issue. I also have Genres like `British / Pop / Soft Rock / Rock / 80S/ Ballad / Classic Rock` and don't see a point to have represented them in such way.

FYI: this tags was automatically set from MusicBranz db, when I imported my music using [beet](http://beets.io) tool.

We can introduce a special setting where user can set delimeter, maybe even per server setting.

**Comment by ogarcia** [comment]
In my case I'm using `beet` too with [lastgenre](http://beets.readthedocs.io/en/v1.4.6/plugins/lastgenre.html) plugin and every song have its own genre.

But @Tapchicoma if you consider that is a useful feature, we can reopen the issue as FR.

**Comment by Tapchicoma** [comment]
Let reopen it. 

@innerspaceboy note that it may not be implemented soon as current focus is on the app lower layers rewriting.

**Comment by innerspaceboy** [comment]
My sincere thanks for your reconsideration! I use Ultrasonic actively 8+ hours daily, and I created [a tutorial feature video](https://www.youtube.com/watch?v=kjj_cJKWH5w) that I shared with my 20,000 readers to spread the word about this magnificent app showcasing the features which set it apart from the original Subsonic. I'll wait as long as it takes for this enhancement implementation and will be grateful to see the feature realized.

Thank you for all your hard work.

**Comment by lachlan-00** [comment]
I don't think this is an issue for ultrasonic. (as an outsider/Ampache developer)

A correct genre tag is multiple tags for each item
* Genre = Rock
* Genre = Electronic

Your tags are single genres split with a delimiter
* Genre = Rock; Electronic

What should be happening is that the server software should be splitting this up for you.

**Comment by innerspaceboy** [comment]
Thanks for your input, @lachlan-00.

As described in [my second comment](https://github.com/ultrasonic/ultrasonic/issues/186#issuecomment-376283162) on this thread, semicolon delimiters are the standard for multiple genre tags as demonstrated by the ten applications I named which employ ";" delimiters for multi-genre support and the six additional applications which I’ve discovered do the same in the year’s time since my original post.

There are several threads about multi-genre support for their respective players. As I stated, multi-genre tags are supported by:

- Foobar2K
- Quod Libet
- Clementine
- MediaMonkey
- Lollipop
- MusicBee
- PowerAmp
- Slimserver
- Windows Media Player
- and gMusicBrowser 

And more recent search results add support by:

- Bliss
- PlayerPro
- Kodi
- Helium
- AIMP
- and pending support for GoneMAD

And as I said nearly all (if not all) of the above use ";" as the default separator.

As discussed [here](https://superuser.com/questions/354646/is-there-media-player-with-support-of-multiple-genre-tags), MediaMonkey, MusicBee, Foobar2000, and Windows Media Player each support multiple genre tagging using ";" as a delimiter.

Bliss similarly supports ";" separated genres as reported [here](https://www.blisshq.com/music-library-management-blog/2011/03/12/multiple-genres-in-mp3s/
). 

The same request was submitted for PlayerPro for Android [here](https://aplayerpro.com/forum/viewtopic.php?f=2&t=868).

There is also a discussion on Quora [here](https://www.quora.com/Is-there-any-Android-music-app-that-supports-multiple-artists-or-genres
) which reports that Kodi, Helium, AIMP, and Foobar support multiple genres.

And the feature request was submitted for GoneMAD [here](https://trello.com/c/axSdPyZ7/60-support-multiple-genres-per-song).

So there is unequivocally a demand and a usefulness of support for semicolon delimited multi-genre tagging across the spectrum of media players. Alternatively, permitting a user-defined delimiter adds even more flexibility for users who don't want to re-tag in excess of half a million files just to use Ultrasonic to its fullest potential. Either way, it would be a wonderful addition to an already powerful application.

**Comment by lachlan-00** [comment]
That's all true but it's a subsonic, /air/libre/*sonic issue rather than the client.

For example, Ampache as a subsonic server does this for you. It also already includes a delimiter option to go beyond the defaults.

A server client should show what it's been given which is why I don't think this is ultrasonic's problem

**Comment by innerspaceboy** [comment]
Ahh, I see. Thank you for the clarification! I'll wait to see what @ogarcia and @Tapchicoma think. It sounded like they thought it could be done in Ultrasonic, just in a matter of time. In the mean time I'll explore Ampache for that particular feature. Thanks again!

**Comment by tzugen** [comment]
Yes, I agree with @lachlan-00 , 
this can't be implemented in the client at a low cost and needs to be done in the servers
