### ISSUE TITLE
New Logo For Ultrasonic

### ISSUE THREAD

**Issue by mirzazulfan** [ultrasonic/ultrasonic#195]
Hi, I designed a logo for your project. If you like it, you can use it. I will send you files. free for your project. Best Regard.
![ultrasonic](https://user-images.githubusercontent.com/36124339/38850082-03272158-423a-11e8-9e90-5742219ac0ec.png)

**Comment by ogarcia** [comment]
Thanks by the effort but we have a new logo in the [beta channel](https://play.google.com/apps/testing/org.moire.ultrasonic).
