### ISSUE TITLE
Album art in album list is not height-restricted

### ISSUE THREAD

**Issue by carlreinke** [ultrasonic/ultrasonic#198]
## Problem description

![screenshot](https://user-images.githubusercontent.com/11667451/40523918-10d23004-5f95-11e8-9cee-6cde5a6bb818.png)

### Steps to reproduce

- Server provides non-square album art where the height is equal to the size requested in the API call and the width is less than the size requested.
- Album art is viewed in album list.

## System information

 * **Ultrasonic version**: 2.4.0

**Comment by Tapchicoma** [comment]
Fix will be available in the next release (2.6.0)
