### ISSUE TITLE
Bookmarks not working

### ISSUE THREAD

**Issue by MidnightSnowleopard** [ultrasonic/ultrasonic#199]
## Problem description

Bookmarks are saved to the server but attempting to play them from the Ultrasonic app results in restarting the track instead.  Can find no way of actually resuming the track at the bookmark position.  Bookmarks menu item shows that there is a bookmark but not how far into the track the bookmark position is.

Tested against Madsonic  6.2.9080.2a5cd1f.20161222.0530, Airsonic 10.1.1-RELEASE, Booksonic 1.1.beta1.  Same results on all servers

### Steps to reproduce

Set a bookmark on any file and then attempt to resume playing from the bookmark.

## System information

 * **Ultrasonic version**:  2.4.0
 * **Android version**: 6.0.1
 * **Device info**: SM-G928T

**Comment by Tapchicoma** [comment]
From quick investigation, I see that it should resume playing from saved song position. But seems it is not working, as I can also reproduce it.

**Comment by Tapchicoma** [comment]
Should be fixed in next release. Feel free to reopen if it will not still working for you.
