### ISSUE TITLE
Can  not connect to  Nextcloud Music

### ISSUE THREAD

**Issue by FadeFx** [ultrasonic/ultrasonic#210]
## Problem description

I have set up my nextcloudpi instance with music app which has built in ampache server, i have temporarly enabled http  access to make power ampache work, which did not when force https was enabled in nextcloudpi pannel. So i have power ampache working but dont like to use http nor the interface of power ampache. Trying to connect using ultrasonic with same access details however results in "didnt understand the reply. please check the server address!" as response. 

### Steps to reproduce

Pobably everything sayed above

## System information

 * **Ultrasonic version**: 2.4.0 (latest playstore)
 * **Android version**: 7.1.1
 * **Device info**: ZTE Axon 7 A2017G

**Comment by FadeFx** [comment]
Realized that this is a subsonic client...

**Comment by dave-kennedy** [comment]
Can this issue be reopened now that Nextcloud Music includes a Subsonic server?

**Comment by paulijar** [comment]
For the record, the compatibility of ownCloud/Nextcloud Music with UltraSonic has been fixed in the Music app version 0.14.1.
