### ISSUE TITLE
Can't connect to instance

### ISSUE THREAD

**Issue by rrrnld** [ultrasonic/ultrasonic#216]
## Problem description

Hi! I'm running the [latest airsonic release](https://github.com/airsonic/airsonic/releases/tag/v10.1.1) and wanted to check out ultrasonic. I installed it from F-Droid, set up my instance, tested the connection and everything seemed to be fine. When I go back however I just can't seem to select it. I tried removing it and adding it again... clicking on "Select Server" just gives me one option, "Offline". 
Am I missing something?

## System information

 * **Ultrasonic version**: 2.6.0
 * **Android version**: 8.1.0 (LineageOS)
 * **Device info**: Xiaomi Mi 5
* **Airsonic version**: 10.1.1

**Comment by ogarcia** [comment]
Maybe you have Ultrasonic in a inconsistent state. Please uninstall and reinstall it (or go to Android Settings -> Apps and delete its files). Next run app, go to _Settings_ -> _Add server_, add your server, go back and sure that in servers section you have the _Add server_ option and your server. Now in main screen you can select _Offline_ or your server pressing in _Select server_.

**Comment by rrrnld** [comment]
So I did what you said:

1. I removed all app data and unninstalled the app
2. I reinstalled version 2.6.0 from F-Droid
3. I opened the app and got greeted with a dialog about the setup being incomplete. I was asking me whether I'd like to add a server, which I did
4. I went to settings, click add server, add my server and enter my credentials. "Test connection" tells me everything is fine
5. After hitting the back button the server is listed under the "Add server" button
6. I hit back once more, click on "UltraSonic Main", "Select Server" and the only option is offline

Is there any way I could help with debugging this?

**Comment by ogarcia** [comment]
Do you put any name in _Name_ field into server settings? If you not put a name it not appear in list.

**Comment by rrrnld** [comment]
Ooooooh, of course! No, I didn't. And it seems to be working fine now. I thought it would just take the URL as the name. Thanks for your help! I don't know if you want to close this. Might be a UI problem? Might also not be one since I seem to be the only person with this issue so far. :D

**Comment by ogarcia** [comment]
Yes, is an issue, but I have open a new bug report with a better description. Thanks @heyarne !
