### ISSUE TITLE
If server name is not defined in server settings then it not appear in server selector

### ISSUE THREAD

**Issue by ogarcia** [ultrasonic/ultrasonic#217]
## Problem description

As has happened in the issue #216, if server name is not defined in server settings then it not appear in server selector.

### Steps to reproduce

1. Go config.
2. Add a server.
3. Set server URL, username and password, leave name in blank.
4. Test connection, it works fine.
5. Go back to main screen and try to select this server. Cannot because no name.

## Posible fixes

We can set server name as mandatory field or use server URL in case of server name is not defined. I think that second option is better, but maybe is more difficult to implement that the first one.

**Comment by Tapchicoma** [comment]
I am also thinking that using server url will be better approach.

**Comment by Tapchicoma** [comment]
Can be fixed in server settings screens refactor story: #90
