### ISSUE TITLE
MediaPlayer stopping and restarting on API version 21

### ISSUE THREAD

**Issue by albertolalanda** [ultrasonic/ultrasonic#218]
## Problem description

My phone is on API 21 and the media player has occasional bugs of stopping and restarting or not starting after loading the new song.

## System information

 * **Ultrasonic version**: 2.6.0 version on github
 * **Android version**: 21

## Additional notes

The new version on the play store has those problems fixed, so could that code be shared here?

**Comment by Tapchicoma** [comment]
nothing was changed regarding `MediaPlayer` class in the new release :thinking: 

Also in long term app may migrate to use ExoPlayer for playback.

**Comment by ogarcia** [comment]
@albertolalanda What is your device? And, have the original firmware?

**Comment by albertolalanda** [comment]
Ok, actually the problem was in a modified version made by me, that wrongly deleted songs when they where loaded into a new playlist, sorry about that 😅.
I thought that this problem was in the latest ultrasonic version as well because when i installed it the same problem ocurred, however that was most likely because of the music files downloaded before by my modified version, that i did not delete.

With that said, me and a colleague are using ultrasonic for a final project, and where wondering if it is ok with all of you.
The project consists of a modified airsonic server and ultrasonic app, that, briefly, let a user listen to music transcoded by a randomly selected codec and bitrate, and allow the user to rate the audio quality of the track. In the server we gather those ratings and expect to analise the results for a report.
The code is currently available here: https://github.com/albertolalanda/new-ultrasonic-fork-for-MyMusicQoE (I just cloned the ultrasonic project and changed the remote url, maybe i should have made a fork?)

**Comment by ogarcia** [comment]
@albertolalanda no problem with clone. Ultrasonic is licensed as GPL3 and you can clone it, modify it and distribute it. As long as you fulfil the license terms, no problem.

Ah, and we are open to Pull Requests, if you can help to close any issue, fell free to do it! :wink:
