### ISSUE TITLE
Fallback to file list when no track number tag found

### ISSUE THREAD

**Issue by 4oo4** [ultrasonic/ultrasonic#219]
## Problem description
I have a number of files with the tracks numbered vinyl-style (A1, A1, B2...), and Ultrasonic does not order them correctly in an album view. I don't think Airsonic parses them correctly, even though they are in the FLAC tags, when I do edit tags on the file the Track tag is blank. However, in Airsonic the files are still listed in the correct order, since the files start with the track number.

Is it possible to have Ultrasonic fallback to sorting files alphabetically when it can't find a track number? I think that's the behavior that the Airsonic web client does in that situation.

### Steps to reproduce
 1. Import files into Airsonic, with Track Number FLAC/ID3 tags as A1, A2...
 2. Browse to album in Airsonic, all tracks have -1 for the track number and are in random order

## System information

 * **Ultrasonic version**: 2.6.0
 * **Android version**: 8.1.0
 * **Device info**: OnePlus 5T

Cheers

**Comment by Tapchicoma** [comment]
Would be very helpful if you can provide several files with such tags. Can send them via gitter.

**Comment by 4oo4** [comment]
Can do, I'll try and do that tonight.

**EDIT:** Linked to an example in Gitter, this is what it looks like in the app:

![screenshot_ultrasonic_20180801-201309](https://user-images.githubusercontent.com/15698835/43556881-8e180754-95f1-11e8-89a7-7a2fcddc7e81.png)

**Comment by 4oo4** [comment]
I was poking around to see how hard this would be to implement, and I'm thinking that this might be the culprit:

https://github.com/ultrasonic/ultrasonic/blob/master/ultrasonic/src/main/java/org/moire/ultrasonic/util/EntryByDiscAndTrackComparator.java

Then one could potentially look here to look at the file listing?

https://github.com/ultrasonic/ultrasonic/blob/master/ultrasonic/src/main/java/org/moire/ultrasonic/util/FileUtil.java

Would that be a good way of approaching it?

I haven't really worked with Java/Kotlin much, but would be willing to take a stab at it if my hunch is correct.

**Comment by tzugen** [comment]
Is this still happening?

**Comment by 4oo4** [comment]
Sorry, forgot this was still open. Since I've been stuck at home I haven't used Ultrasonic for a while, but I will test this once I get my Airsonic server recovered from a hardware failure and let you know.

Cheers

**Comment by ogarcia** [comment]
Please, check with latest beta. If still present, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
