### ISSUE TITLE
Some files in playlists are not marked as pinned in offline mode

### ISSUE THREAD

**Issue by topas-rec** [ultrasonic/ultrasonic#222]
## Problem description

Some files in playlists are not marked as pinned in offline mode, though they were successfully pinned and downloaded in online mode before.
The files have a pin logo in online mode and no pin logo or downloaded logo in offline mode. The files are physically on the device and are playable through stock player.
ultrasonic cannot play these files and starts showing "buffering" when I attempt to play an affected file.
I guess about 1%to 10%of all synced files are affected.

I cannot see what the difference between the songs is. It looks like they all have a `0-1-...` in their file name. (But this seems not likely to cause this issue)

How can I further debug without setting up the whole project on my PC?

### Steps to reproduce

Open a playlist in online mode with enough files and select all files and pin them. Wait for all files to be downloaded. Check if all files are marked as pinned. Go in offline mode. Go to the recently pinned playlist and check if all songs are marked as pinned.

## System information

 * **Ultrasonic version**: 2.6.0
 * **Android version**: 7.1.2
 * **Device info**: LG G4 (H815)

## Additional notes
(Comments below screenshots)

![screenshot_20180809-071823](https://user-images.githubusercontent.com/20391449/43882903-a83fde52-9bb1-11e8-81e7-f7a8120b7a0c.png)
Online mode. Playlist completely pinned
![screenshot_20180809-071934](https://user-images.githubusercontent.com/20391449/43882918-b9dff17e-9bb1-11e8-803b-20451215cd48.png)
Offline mode. Playlists has unpinned songs.
![screenshot_20180809-072141](https://user-images.githubusercontent.com/20391449/43882963-dabefe3a-9bb1-11e8-9e7b-4e11ae2fcfb1.png)
Playlist file contains the correct entries.
![screenshot_20180809-072213](https://user-images.githubusercontent.com/20391449/43882997-f4f2a2f2-9bb1-11e8-9303-ec9f98a7e1a4.png)
Other music player shows the unpinned songs in its playlist view and can play the songs.

Another song has the same issue in ultrasonic and external players CANNOT play or list the files, too.
Look at the song "The spy hunter"

![screenshot_20180809-071911](https://user-images.githubusercontent.com/20391449/43883125-62a634ee-9bb2-11e8-8693-1b3148c0167c.png)
Online mode. Playlist pinned.
![screenshot_20180809-071954](https://user-images.githubusercontent.com/20391449/43883140-741e70ec-9bb2-11e8-8560-93e4919eec0f.png)
Offline mode. Songs unpinned.
![screenshot_20180809-072120](https://user-images.githubusercontent.com/20391449/43883194-a50a0432-9bb2-11e8-9ac4-86f52694f72e.png)
Playlist file.
![screenshot_20180809-072327](https://user-images.githubusercontent.com/20391449/43883213-b3f663c8-9bb2-11e8-8538-73839c95fbb8.png)
Song missing in external player, too. (Song IS playable by external player not using the playlist view. Just select the song and play)

**Comment by topas-rec** [comment]
I have setup an android project with my server and I#m able to run the app in the emulator of Android Studio. The issue is reproducible.
Can someone tell me where to start debugging?

**Comment by ogarcia** [comment]
This is not a bug. In offline mode you can see all files that you have in your device, cached and pinned.
