### ISSUE TITLE
Switch to "Offline" if server is not accessible

### ISSUE THREAD

**Issue by carlreinke** [ultrasonic/ultrasonic#225]
## Problem description

If I open UltraSonic and the server that was last selected has a host name that cannot be looked up then the application shows an error message and then closes.  It is not possible to do anything to fix it until the host name look-up succeeds again.  Instead the application should switch to "Offline".

### Steps to reproduce

1. In UltraSonic, add a server with a host name that's only available on your local network -- ex. "http://computername.lan:4444".
1. Select the server in the "Select Server" picker.
1. Close UltraSonic (and swipe away in recent apps so that the activity terminates.)
1. Disable wifi.
1. Open UltraSonic.  Error dialog appears: "A network error occurred.  Please check the server address or try again later."
1. Press "OK".  Dialog closes and UltraSonic closes.

## System information

 * **Ultrasonic version**: 2.5.0
 * **Android version**: Android 8.1
 * **Device info**: Google Nexus 5X

## Additional notes
It doesn't matter if the server isn't running.  As long as the host name look-up succeeds, the error dialog doesn't appear and you can use the server picker again.

**Comment by carlreinke** [comment]
The problem with the application closing might be fixed in 2.6.0 via #211.  I haven't tested because the 2.6.0 APK on the GitHub release page refuses to install over the version installed from the Play Store.

**Comment by ogarcia** [comment]
Already fixed. See #226 to install latest version from Play Store.
