### ISSUE TITLE
Offline mode does not show Opus files.

### ISSUE THREAD

**Issue by carlreinke** [ultrasonic/ultrasonic#227]
## Problem description

UltraSonic can play Opus files, but they do not appear when in offline mode.

### Steps to reproduce

1. Play/cache a `.opus` file from a server.
1. Switch to offline mode
1. Track/file does not appear anywhere.

## System information

 * **Ultrasonic version**: 2.6.0
 * **Android version**: 8.1
 * **Device info**: Nexus 5X

**Comment by topas-rec** [comment]
@carlreinke can you check if the issue is similar to #222 ?
In #222 I have ogg files that are not showing up AND mp3 files, too.

**Comment by carlreinke** [comment]
If I rename a .opus file to .ogg then it shows in offline mode and is playable.

**Comment by topas-rec** [comment]
Do you rename the files on the server or on device?

**Comment by carlreinke** [comment]
On the device.

**Comment by topas-rec** [comment]
Ah I see.
All my files obviously get transcoded to mp3. I don't have any other format on my device.
The screenshots of #222 show that files are transcoded from ogg to mp3.
So these issues are most likely not related.
