### ISSUE TITLE
Allow both external and internal addresses for server

### ISSUE THREAD

**Issue by deusxanime** [ultrasonic/ultrasonic#235]
I've been trying out a few different Sub/Mad/Airsonic apps (I use Airsonic in a docker container for my server) and I was confused for a bit because it seems there is no way to add both an internal and external address/URL for a server in Ultrasonic. The other apps I've tried are D-Sub and Substreamer and they both allow you to input an internal address for your server. Since many people, such as myself, use port forwarding on our routers to get access when not at home, it causes an issue where an external address, such as http://music.mydomain.com:4040/ will not work/resolve when on the same local network as your server (unless you run your own DNS and can add it which not many do). Therefore when on your local network you would use http://192.168.0.100:4040/ or something similar instead. The other apps I mentioned both allow for that and decide which to use based on the Wi-fi name you are connected to I believe.

For Ultrasonic, there is only one server address you can use, so I can see two options. You add your internal and external addresses as two separate servers and switch between them depending if you are at home or not. But that would introduce two different servers, which I think would mean Ultrasonic would see them as different and maintain separate playlists and potentially cached songs? The other option is to just have one server listed and manually change the URL depending where you are. That way only one sets of playlists and cached data exists hopefully at least. But then you have to remember to change it back again every time you switch between home and out. Right now the latter seems to be the best option, but ideally I think it would be handled by the app similar to how I've seen it in other clients as described above.

I tried searching the issues and was surprised not to see this already requested (unless I missed it), so I thought I'd open an issue as a feature request.

**Comment by Tapchicoma** [comment]
I solved this problem by using dns: dns at home points to internal address, common internet dns - to internet address. Though this solution requires advanced knowledge of how to configure dns.

Solution with adding second server address and manual switching sounds like just adding second server in the current app.

Solution with automatic switching is more promising, and, personally I would go with it.

**Comment by deusxanime** [comment]
Yeah, manually changing the address or server is definitely more of a "workaround" I tried to think up with what is given and currently possible.

Ideally you could input them both in a single entry and have it automatically switch in a similar way to the other apps. It was seamless with them and I never even had to worry about it.

**Comment by nroach44** [comment]
@deusxanime You can also configure hairpinning on the router to allow accessing the port forwarded version from the inside. It's a fairly advanced thing, so some routers might not support it.

**Comment by ogarcia** [comment]
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
