### ISSUE TITLE
Recently added album list sort issue

### ISSUE THREAD

**Issue by arnomx** [ultrasonic/ultrasonic#236]
## Problem description

I have been switching from Libresonic to Airsonic recently, and I noticed that since this switch the recently added album list is not sorted in the right way in Ultrasonic only (it is correct in Airsonic web UI, and also in standard Android Subsonic player).

Sort order in Ultrasonic seems to be done by subsets : within a batch of recently added albums, items are sorted by alphabetical order. I have no idea of the criteria that directs batches split.

### Steps to reproduce

Simply pull to refresh the recently added albums list when connected to an Airsonic server.

## System information

 * **Ultrasonic version**: 2.5.0
 * **Android version**: 6.0.1
 * **Device info**: Google / LG Nexus 5
![airsonic web ui - recently added - 1](https://user-images.githubusercontent.com/37321749/46780907-3fa10e80-cd1f-11e8-86ab-81cfc851cb94.jpg)
![airsonic web ui - recently added - 2](https://user-images.githubusercontent.com/37321749/46780908-3fa10e80-cd1f-11e8-980b-cfeba5c3fb74.jpg)
![subsonic - recently added - 1](https://user-images.githubusercontent.com/37321749/46780909-3fa10e80-cd1f-11e8-949a-d68e17ee29ec.png)
![subsonic - recently added - 2](https://user-images.githubusercontent.com/37321749/46780910-3fa10e80-cd1f-11e8-99a8-30c4ba09812c.png)
![subsonic - recently added - 3](https://user-images.githubusercontent.com/37321749/46780911-3fa10e80-cd1f-11e8-87f4-58aded0fa0c0.png)
![ultrasonic - recently added - 1](https://user-images.githubusercontent.com/37321749/46780912-4039a500-cd1f-11e8-8810-3584279b8973.png)
![ultrasonic - recently added - 2](https://user-images.githubusercontent.com/37321749/46780962-97d81080-cd1f-11e8-91d2-38027d6a57d0.png)
![ultrasonic - recently added - 3](https://user-images.githubusercontent.com/37321749/46780963-97d81080-cd1f-11e8-8a0b-6e31b95b293e.png)

**Comment by punk3r70** [comment]
I had the same problem until I unchecked the option 'Sort Songs By Disc'. Don't understand the correlation but now it sorts as it should.

**Comment by arnomx** [comment]
You're right, unchecking this option gets the sort order back, and titles
are still sorted by disc in multi-disc albums ; weird, no ? Not sure if
this should be considered as solved or not ; it did not behave this way
with libresonic or subsonic, only with airsonic.

Anyway, thank you for the tip !

**Comment by ogarcia** [comment]
The option _Sort Songs By Disc_ short albums alphabetically. When you ask to a server for recently added albums, the server gives you a list sorted by newer to older. When you check this option the list is shorted alphabetically.
