### ISSUE TITLE
NextcloudSnap-Airsonic-Ultrasonic: Several Problem in Video Playback

### ISSUE THREAD

**Issue by qwertyuser1983** [ultrasonic/ultrasonic#241]
UPDATE The issues have been mirrored on https://github.com/airsonic/airsonic/issues/873

Dear Admin, 

When using my personal server, when streaming videos, and picking "which minutes part we want to play" (the timing bar), either could happen, 
- we simply can't pick which minutes, or
- we can, forward, but not backward, or
The playback end and the app return to main video list. 
???

(｡•́︿•̀｡) 

Renan 

The server is Airsonic from Linuxserver Docker. UPDATE The video files is stored in Nextcloud-Snap.
The mobile phone is either Nokia 6 Android or Advan i7D
The server is http. 
The video playback app is either VLC or MX Player
All functions, especially random playback, work great. 

(* ^ ω ^)

**Comment by Tapchicoma** [comment]
It is possible that it is server streaming implementation limitation.

**Comment by retro-78** [comment]
Hi 

I always had this problem with video playback with the Android app. I think some meta data are missing somewhere when reading a video and then the playback is broken. It could very nice if this problem gets fixed because the video transcoding is working but we can't use it on mobile devices.

**Comment by qwertyuser1983** [comment]
> It is possible that it is server streaming implementation limitation.

Make sense. 

I am using a similar implementation with Ampache, like BeGo comment in https://arielelkin.github.io/articles/easily-sync-and-stream-your-entire-music-collection-using-docker.html 

I set Airsonic to access the multimedia files directly from Nextcloud Snap repo.

**Comment by Tapchicoma** [comment]
Currently app just passes url to the server stream to external videoplayer, so on the app side no so much can be done. I think it is worth to open an issue in Airsonic repo (or for server that you are using).

**Comment by qwertyuser1983** [comment]
> Currently app just passes url to the server stream to external videoplayer, so on the app side no so much can be done. I think it is worth to open an issue in Airsonic repo (or for server that you are using).

OK, I have opened a sister issues in Airsonic Repo. Thanks for the hint. :)
