### ISSUE TITLE
"cache size" setting is not respected?

### ISSUE THREAD

**Issue by ToxicFrog** [ultrasonic/ultrasonic#242]
## Problem description

In the settings, I have the following:
- cache size: 100MB
- songs to preload: unlimited
- directory cache time: disabled

My expectation was that this would cause it to preload as many songs as it could fit in 100MB, then stop. Presumably at some point it would start expiring old songs (when they've already been played? After they haven't been played for some period of time?) which would allow it to preload more.

Instead, the "cache size" setting seems to be completely ignored. It has so far cached 2GB of songs.

### Steps to reproduce

Set the cache settings as above.
Select an artist or genre or album or whatever that exceeds the 100MB cache size and hit play.
Wait for it to finish preloading and then inspect the size of the cache directory (using OI File Manager or similar).

## System information

 * **Ultrasonic version**: 2.5.0
 * **Android version**: 9
 * **Device info**: Google Pixel (v1, non-XL)

## Additional notes

I'm not sure if this is Ultrasonic not working as intended, or if it's working as intended but the intentions are not clear from the option names. In the latter case, clearer documentation of what the various options do would be a great help.

It's also not clear to me how, or if it's even possible, to get the behaviour I _really_ want, which is to cache the next N songs in the playlist up to some size limit and expire already-played songs after a day or two, allowing me to seek both forward and backward in the playlist even when offline.

**Comment by Tapchicoma** [comment]
I think it is intended behaviour of current cache implementation as there is cleaup task (check `CacheCleaner` class) that shrinks cache size lower then set in the settings.

Theoretically it is also possible that there is some issue in clean logic that leads to this behaviour.

**Comment by ToxicFrog** [comment]
Ok, after rummaging through `CacheCleaner` I think I have some understanding of this:
- The downloader does not care about cache size or free space at all, it just downloads the next (1..infinity) files in the current playlist. Files so downloaded are added to the `downloadList` which prevents them from being deleted. The list is cleared when the playlist is cleared or replaced, but apart from that, as far as I can tell, files in the playlist which are marked for download will stay in the list.
- The cache cleaner has two modes but for the purposes of this bug they're basically the same. One runs after downloading each file (I think), the other...on program startup? When a new download manager is created? Periodically? Not sure about this.
- The cache cleaner works by sorting all the files by modification time ascending, removing any files that are still in the download list, and then deleting files, oldest first, until (a) the cache is smaller than the cache size limit and (b) there's at least 500MB free on the filesystem.

So, in practice, what this seems to mean is:
- the downloader wants to download the song you're listening to + the next "Songs to Preload" songs.
- once downloaded, those files will remain on disk as long as they're in the playlist, no matter what your cache settings are.
- once a file is no longer in the playlist the cache cleaner is capable of removing it.
- the cache cleaner removes the oldest files first and tries to both keep the cache size under the configured limit and retain at least 500MB of free space.

The downloader does not seem to respect the 500MB free space reservation, so it looks like it may be possible to run out of free space despite that if you have a sufficiently large playlist, but there may be some last-ditch safeties there that I've missed.

Overall this seems like a pretty reasonable way to behave, but it could stand to be documented better. :) It would also be nice if it were possible to set "songs to preload" to any value -- the gap between "10 songs" and "infinity songs" is pretty wide, and it'd be nice to be able to set it to, say, 30 songs to reliably cover the length of my commute.

**Comment by Tapchicoma** [comment]
Really nice investigation :+1: 

In general what is your vision of `cache size` setting behaviour? Should it stay like at it is or should be __really__ max size for cache, even if song size exceeds it?

**Comment by heinhuiz** [comment]
I would like to reopen this issue with an answer to the last question. I ran into the same problem as OP, because I assumed that the max size would really be the actual maximum size of the cache.
My playlist is >1000 songs and sometimes I am disconnected from the internet for several days. I would really like it if I could set a maximum for the cache to a high number of Gigabytes and cache all the songs that fit inside. Caching only 10 songs is not nearly enough for my use case.
