### ISSUE TITLE
Connection error with airsonic 10.2

### ISSUE THREAD

**Issue by b1rger** [ultrasonic/ultrasonic#245]
## Problem description

I updated my airsonic instance to 10.2 a couple of days ago. Since then UltraSonic says
`A network error occured. Please check the server address or try again later.` when trying to select a folder in the Media Library

## System information

 * **Ultrasonic version**: 2.6.1
 * **Android version**: LineageOS 15.1 (Android 8.1.0)
 * **Device info**: Nexus 5x

Thanks for UltraSonic!

**Comment by ogarcia** [comment]
@bschacht I try today with latest version and Airsonic 10.2.1 and not have any problems. Are you sure that you are using latest version and that you can reach your server from your device (for example using web browser)?

**Comment by b1rger** [comment]
hm, weird, after removing and readding the server connection in ultrasonic, it works again. sorry for the noise!
