### ISSUE TITLE
Show album error in the contextual menu of the play queue

### ISSUE THREAD

**Issue by epoupon** [ultrasonic/ultrasonic#249]
## Problem description

In the playque, a long press on a track will propose 'Show Album', 'Show Artist', etc..
'Show Artist' works fine, but 'Show Album' emits a getArtist request using the id of the album. 

### Steps to reproduce

Everything you need is in the problem description.

## System information

 * **Ultrasonic version**: 2.5.0
 * **Android version**: 4.4.2
 * **Device info**: 

## Additional notes

Include any extra notes here. Otherwise you may remove this section.

**Comment by epoupon** [comment]
Seems to be a duplicate of #208

**Comment by ogarcia** [comment]
Please, update Ultrasonic to latest version
