### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by epoupon** [ultrasonic/ultrasonic#250]
## Problem description

Navigation -> Search is not working. It just displays 'Click to Search' and nothing appears (no Search field on top of the screen, no keyboard showed)

### Steps to reproduce

See problem description.

## System information

 * **Ultrasonic version**: 2.5.0
 * **Android version**: 8
 * **Device info**: Sony Xperia XZ1, french language

**Comment by ogarcia** [comment]
I can't reproduce your issue. Can you attach a screenshot?

**Comment by epoupon** [comment]
Really weird, I just tried again and it seems to work fine now.
I will put a screenshot as soon as the problem appears again.
