### ISSUE TITLE
First song in a playlist stops playing

### ISSUE THREAD

**Issue by DrAndri** [ultrasonic/ultrasonic#252]
I'm having a problem where the first song in a playlist stops playing.
Originally intended to comment on #228 but my symptoms are a little different

It's always and only the first song in a playlist that stops playing and it's always near the end of the song. 
The progress bar and the timer move at double speed. Half way through the song the progress bar maxes out but the timer keeps going past the length of the song. When it pauses it always snaps to having one or zero seconds left and says it's playing (the pause button is visible) but the timer is halted. 
If I press next it starts the next song and plays the rest of the playlist fine, no problems at all. If I play the first song again it does not happen. 

## Steps to reproduce
1) Play an album
2) Watch progress bar go at double speed, wait till end of song and it pauses

It doesn't seem to matter whether the device is sleeping, on WiFi or playing through bluetooth, it happens consistently every time when streaming, not with cached files. I have battery saver and optimization turned off

## System information

 * **Ultrasonic version**: *2.6.1*
 * **Sonic version**: *Airsonic 10.4.0*
 * **Android version**: *8.0.0*
 * **Device info**: *Moto Z2*

**Comment by ogarcia** [comment]
@DrAndri this still happens with current 2.11 version?
