### ISSUE TITLE
how can I debug ultrasonic errors?

### ISSUE THREAD

**Issue by lachlan-00** [ultrasonic/ultrasonic#255]
Hey this is more of a question than an issue.

I've made a lot of changes to ampache's subsonic API and there is an issue with the json response when getting podcasts and episodes. (Ampache converts XML to json)

The json seems okay but the error message in ultrasonic doesn't say anything about why it doesn't like the response.

Does the project source load in Android studio and can i debug using the emulator from there? Or can I get log output on a rooted phone somehow?

**Comment by lachlan-00** [comment]
I fixed my ampache issue but would still like to know how it's done in android

**Comment by Tapchicoma** [comment]
You should build and install debug build via `./gradlew installDebug` command or Android Studio.

To see logs either:
- open "logcat" tab in Android Studio
- use `adb logcat` command
- use [pidcat](https://github.com/JakeWharton/pidcat) library that is a wrapper on the command above

**Comment by lachlan-00** [comment]
Thank you for this.
