### ISSUE TITLE
FR: support download.view

### ISSUE THREAD

**Issue by lachlan-00** [ultrasonic/ultrasonic#257]
I'm just looking through the code and I see that ultrasonic only sends stream requests to the server.

What I'd like is to have the choice to send download requests when caching.

I'm new to android but I'll try to make a pull based on scrobbling being enabled. 

I.e. if I enable scrobble support then only send download.view requests

**Comment by tzugen** [comment]
@lachlan-00 What is the difference between requesting stream and download?

**Comment by lachlan-00** [comment]
If you request a download you are caching the song to play later.

If you request a stream you are playing the song now.

Implications are for now playing, stat tracking and things related to your activities.

Stream 100 songs in 8 mins? Or download 98 and play 2.

**Comment by tzugen** [comment]
So the server returns the same file, but scrobbling etc. is handled differently?

**Comment by lachlan-00** [comment]
> So the server returns the same file, but scrobbling etc. is handled differently? 

The server could do something differently like return an original file or different bitrate but in general it's the same file.

To the client application it doesn't really mean much but it requires workarounds to determine playback intent from the server.

When you send a download or a stream the intent is clearer

**Comment by tzugen** [comment]
This would be relatively trivial to fix:
getDownloadInputStream is used only in DownloadFile, L254

We could check `Boolean save` and then use download.view or stream.view

**Comment by tzugen** [comment]
Hey, I opened a PR.
If you can, could you test it?

**Comment by lachlan-00** [comment]
> Hey, I opened a PR.
> If you can, could you test it?

Sure, I'll check it out on Monday
