### ISSUE TITLE
Connection failure. Trial period is over.

### ISSUE THREAD

**Issue by jasonpriestly** [ultrasonic/ultrasonic#259]
Hello,

Getting this popup error on Ultrasonic when I try to connect to my server:

"Connection failure. Trial period is over."

Using the version currently up on the Play store, and the one on GitHub, same error both.

Tried various devices, all running different versions of Android.

Thanks.

**Comment by ogarcia** [comment]
Please read Subsonic documentation: Also note that after a 30-day trial period you need to upgrade to Subsonic Premium to use the apps. By upgrading you also get other benefits.
