### ISSUE TITLE
Playback is paused when any bluetooth device disconnects in case multiple are connected

### ISSUE THREAD

**Issue by mjanssens** [ultrasonic/ultrasonic#266]
## Problem description

Hi, thanks for developing this app, I use it a lot.
Playback nicely pauses when disconnecting a bluetooth device, but apparently there is no check if the device doing the real playback is being disconnected. Playback is paused when any bluetooth device is disconnected.

### Steps to reproduce

The real use case is the combination of my mi band and bluetooth speaker. The mi band connects and reconnects a lot.
But for easier simulation just connect for example a bluetooth speaker and a laptop simultaneously to the android phone.
Start playback in Ultrasonic via the bluetooth speaker, while still connected to the laptop via bluetooth.
Then go to bluetooth settings in android and disconnect the laptop.

Result: Playback is paused.
Expected result: playback should not be paused, only if the real playback device should disconnect, in this case, the bluetooth speaker.
Result in case of mi band: it reconnects a lot, (so that's a problem too, not for this app of course), so playback is paused a lot of times. 

## System information

 * **Ultrasonic version**: *2.6.2*
 * **Android version**: *9, lineageos 16.0*
 * **Device info**: *Oneplus One*

## Additional notes

I'm willing to test any changes to the app.
If you need log files I can get them for you.
I also tested the behavior in other apps, f.e. VLC and they just continued playing.

**Comment by mjanssens** [comment]
Possibly related issue: https://github.com/ultrasonic/ultrasonic/issues/228

**Comment by nitehu** [comment]
This seems to be a "feature", in `BluetoothIntentReceiver` it was added to detect disconnection of any bluetooth device and pause playback (since 2013). Before that it listened only to A2DP events, which is the correct way IMHO.
Maybe this was added to fix something else...

**Comment by ogarcia** [comment]
I think that we should not fix intentional behaviors of Android system

**Comment by fiskhandlarn** [comment]
Could this instead be solved by having a setting in Ultrasonic that ignores Bluetooth disconnections (and keeps playing music until the user actively press pause)?

**Comment by nitehu** [comment]
Sorry I wasn't clear, it is intentionally written in Ultrasonic and not in Android. [This is the commit](https://github.com/ultrasonic/ultrasonic/commit/d76e427bdc0f21e63ec16d1e125843c2b3bb01c2#diff-a01a1a44523672d6ed1223b2fecfe1e3).
The commit message says "Bluetooth adjustments" (there is no linked issue :( )
Not sure why these adjustments were necessary, needs some testing. Or maybe a feature flag, as fiskhandlarn suggested.

**Comment by ogarcia** [comment]
I think that this is a patch because some audio devices are not recognized as A2DP. Maybe we can add a new option under "Playback control settings", next to "Media buttons" like this:
Name: Ignore bluetooth events
Description: Ignore the connection or disconnection of bluetooth devices, this option doesn't affect to media buttons

**Comment by mjanssens** [comment]
Thanks so much!

**Comment by ogarcia** [comment]
Published release! :wink:
https://github.com/ultrasonic/ultrasonic/releases/tag/2.13.0

**Comment by mjanssens** [comment]
Just tested it, works great.
