### ISSUE TITLE
Correct lyrics won't be displayed

### ISSUE THREAD

**Issue by daetsch** [ultrasonic/ultrasonic#270]
## Problem description
Correct lyrics won't be displayed.

### Steps to reproduce
On Android:
Play a song -> show lyrics -> It says correct Artist and Title, but then the lyrics of a complete different song (let's say song "A") is shown. I can play any song I want, I will always see the lyrics of song "A".

On Ampache (what I use as backend):
Correct lyrics for each song is being displayed.

## System information
 * **Ultrasonic version**: 2.7.0
 * **Android version**: 7.1.2
 * **Ampache version**: 4.1.1

**Comment by ogarcia** [comment]
Cannot reproduce it. Still occur with latest version?

**Comment by daetsch** [comment]
Have lost this issue out of sight recently. Played with it a little bit the other days and figured out it was a problem with the Firewall. Works now as it should.
