### ISSUE TITLE
Seek Bar Greyed and Uncontrollable 

### ISSUE THREAD

**Issue by seniorm0ment** [ultrasonic/ultrasonic#273]
## Issue

After a few songs the seekbar goes grey and I'm unable to control the track. I can still skip songs and play/pause, just seeking has trouble. 

Edit: Ok, I think I see what's happening, can it not stream the music? It looks like it downloads/caches the songs, and for some reason it takes forever for no apparent reason.

## System information

 * **Ultrasonic version**: *F-Droid 2.7.0 (it was doing it on the previous version as well)*
 * **Android version**: *Android 9*
 * **Device info**: *LGv40*
* **Server**: *Apache Tomcat/8.5.43, java 11.0.6, Windows 10 (161.5 MB / 238.0 MB)*
* **Server Airsonic Client**: *Airsonic 10.5.0-RELEASE – November 7, 2019 (AdoptOpenJDK)*
  
'

**Comment by seniorm0ment** [comment]
Still having this issue on the latest Airsonic version.
Not sure what's up but seems like network issues overall, relate to my other issue, but it just seems to have trouble with streaming and caching fast.
Again, my network and connection is solid and should be no issues.

**Comment by ogarcia** [comment]
@grravity this still happens with current version 2.11.x?

**Comment by seniorm0ment** [comment]
I think this is related to #271

**Comment by ogarcia** [comment]
Ok. Close this and work in #271 and #228
