### ISSUE TITLE
FEature Request: Also lisit the Starred Songs

### ISSUE THREAD

**Issue by gerroon** [ultrasonic/ultrasonic#276]
Hi

I like this app so far and I am also hapy to see that Jukebox mode works! THis particular feature seems to be broken on Dsub.

I am also happy to see that I can get my all starred albums from the server. Is it also possible to support to list the starred songs in the same view like Dsub can do?

thanks

**Comment by ogarcia** [comment]
You have in main screen: `Songs -> Starred` an you have the list of your starred songs
