### ISSUE TITLE
Restore compatibility with old Bluetooth devices

### ISSUE THREAD

**Issue by nitehu** [ultrasonic/ultrasonic#285]
## Problem description

It seems the handling of Bluetooth events changed in one of the API versions Ultrasonic jumped lately.
There are some Bluetooth devices (e.g. some JVC car audio players) which were able to play/pause Ultrasonic with their single button on older APIs. On API28, the button now only able to start Ultrasonic, and unable to pause it.

### Steps to reproduce

- Get an old JVC car radio :)
- Install Ultrasonic before API28 refactor
- Play/Pause works
- Install Ultrasonic after API28 refactor
- Pressing the button starts playback, but pressing it again won't pause it.

## Additional notes

I'm not a bluetooth stack expert, I only noticed that on new APIs Ultrasonic always receives "KEYCODE_MEDIA_PLAY" keycode, even when the bluetooth device should send pause.
Maybe on older APIs there were a logic in android which would automatically convert the **play** code to **pause** code when **play** is received during playback.
This problem is not unique to Ultrasonic, other media players have it too with these bluetooth devices.

The easy fix would be to treat the **play** keycode as a pause during playback. This behaviour would be turned on/off from the settings.

**Comment by ogarcia** [comment]
@nitehu I love the first step of this bug :joy:
