### ISSUE TITLE
Notification should be dismissable when music is paused

### ISSUE THREAD

**Issue by moviuro** [ultrasonic/ultrasonic#286]
First off, thanks for the great software. I'm moving away from Google Play Music, which is going to [join the Google graveyard by December 31st](https://youtube.googleblog.com/2020/05/youtube-music-transfer-google-play-music-library.html); I'm still learning as I go.

## Problem description

I want to dismiss the Ultrasonic notification when the music is paused, by swiping the notification away. **The "close" button is hard to tap**; however it can still have a use to "stop and kill" Ultrasonic at once when music is still playing.

### Steps to reproduce

1. Play Music
2. Pause music
3. Go to home screen
4. show notifications
5. Swipe the notification away

#### Expected

The notification is dismissed, and Ultrasonic can close.

#### Actual

The gear icon shows and the notification is not dismissed.

## System information

 * **Ultrasonic version**: *2.8.0* (Play Store)
 * **Android version**: *10*
 * **Device info**: *Nokia 7 Plus*

**Comment by ogarcia** [comment]
You must press the close button in notification to close it

**Comment by moviuro** [comment]
> You must press the close button in notification to close it

This is a usability issue. I'm not really fat fingered, but I find it unexpectedly hard to press that button.

**Comment by moviuro** [comment]
![image](https://user-images.githubusercontent.com/6882978/88908660-76c91280-d25a-11ea-8170-257aa84cbccd.png)
![image](https://user-images.githubusercontent.com/6882978/88908680-7cbef380-d25a-11ea-9e6c-602a8494ea07.png)

The close button is seriously tiny, and being able to just swipe the notification away would help.
