### ISSUE TITLE
Notification's close button is too small. It should be possible to dismiss the notification.

### ISSUE THREAD

**Issue by moviuro** [ultrasonic/ultrasonic#287]
This is a usability issue that I tried reporting in #286 .

The close button is too small to be used, and in a bad spot when the notification is "small".

* I can't always close the notification when I want to.
* I did inadvertently close Ultrasonic when I meant to jump to the next track.

![image](https://user-images.githubusercontent.com/6882978/88908660-76c91280-d25a-11ea-8170-257aa84cbccd.png)
![image](https://user-images.githubusercontent.com/6882978/88908680-7cbef380-d25a-11ea-9e6c-602a8494ea07.png)

Being able to just *swipe the notification away* would help a lot.

**Comment by nitehu** [comment]
The swipe seems like a good idea (I always try to swipe away notifications first too, until I notice that some of them only display a setting icon after swiping...), however Android sets the notifications of background services to be "ongoing" type, which can't be dismissed with a swipe. 
The notification needs a redesign nevertheless, maybe we could make something like the new MediaStyle notifications of android, with the color palette handling etc. besides making the buttons larger.
