### ISSUE TITLE
Allow Connecting Over Localhost

### ISSUE THREAD

**Issue by seniorm0ment** [ultrasonic/ultrasonic#289]
When trying to add a server using localhost:port or localip:port it gives an error saying invalid URL.
Also if I connect to a Wi-Fi network that doesn't have WAN access but is connected to the Airsonic server it should have no issues reaching it, UltraSonic does give a popup saying it needs internet connection though.
(No issues doing this with Jellyfin for reference)

Android 10, Ultrasonic F-Droid 2.9.0, Airsonic 10.6.2

**Comment by ogarcia** [comment]
You can use your local IP without problem, but you MUST define the protocol in URL (http or https), for example if your local IP is 192.168.1.1 and you are serving Airsonic via http in port 8090 you must set the following URL:
http://192.168.1.1:8090
