### ISSUE TITLE
Feature request: sleep timer

### ISSUE THREAD

**Issue by svetlemodry** [ultrasonic/ultrasonic#293]
It would be great to have a possibility to set a timer within the application, which would stop playing the music after the preset time.
Thanks for all your work on the app!
Cheers!
J

**Comment by ogarcia** [comment]
Sorry but we do not plan to add functionalities that can be obtained from the system itself. If your Android phone don't have the sleep function in settings you can use any "_Sleep timer_" app from Play Store.
