### ISSUE TITLE
Feature Request: Support "Songs > All" list view

### ISSUE THREAD

**Issue by ackl** [ultrasonic/ultrasonic#294]
## Problem description

Somewhat related to #120 

This is a feature I miss from apps like spotify/tidal where it is possible to show a view listing my entire library.

rn the Songs node only has "Random" and "Starred" as children.

## Additional notes

Could be implemented by doing

for each artist in getArtists ->
    for each album in get getArtist(artist) ->
        get songs from getAlbum(album)

**Comment by ogarcia** [comment]
See #718
