### ISSUE TITLE
jukebox not found

### ISSUE THREAD

**Issue by gonzasiman** [ultrasonic/ultrasonic#296]
Hi, after update the app, the function jukebox not found, the player continuos locally.. 

## System information

 * **Ultrasonic version**:  2.9.0
 * **Android version**: 7.1
 * **Device info**: Motog4play

## Additional notes

Tanks, sorry for my english.

**Comment by ogarcia** [comment]
What is the issue? You open the player -> press three dots menu and -> Start Jukebox. What happens then?

**Comment by nitehu** [comment]
I'm afraid I've left a bug in the Jukebox player. 
When you tap on the menu "Jukebox On", nothing happens. The playback will be started on the phone, not on the server.
Will investigate and get back to you.

**Comment by ogarcia** [comment]
@nitehu OK. No problem. :wink: 

In other hand, @nitehu if you want to be a collaborator with full access talk to me [vía gitter](https://gitter.im/ultrasonic/ultrasonic)

**Comment by gonzasiman** [comment]
@ogarcia sorry for my bad description, @nitehu thanks for understand the problem is exactly what you described above. 
Thanks and sorry again!

**Comment by ogarcia** [comment]
@gonzasiman no problem!!

Fixed in 2.11.1. Can download it from tag in [here](https://github.com/ultrasonic/ultrasonic/releases/tag/2.11.1) or in [play store beta program](https://play.google.com/apps/testing/org.moire.ultrasonic)
