### ISSUE TITLE
No more Jukebox mode

### ISSUE THREAD

**Issue by gerroon** [ultrasonic/ultrasonic#299]
## Problem description

Hi

I think that the jukebox mode has been broken since couple updates ago. It does not work as in the jukebox mode does not play on the server and resets to the device mode. On the otherhand Dsub still can do the jukebox mode fine so I am sure that is not a serverside issue since my server has not gotten a change for months.

### Steps to reproduce

Open Ultrasonic

Open Random in the main menu

Click Play at the right top

Choose "jukebox mode" in  additional settings in the playing now window

## System information

 * **Ultrasonic version**:  2.11
 * **Android version**:  Android 9
 * **Device info**: Samsung S7

## Additional notes

Server: Debian Testing X64, Airsonic 10.6.2-RELEASE,

**Comment by ogarcia** [comment]
Already fixed, see #296
