### ISSUE TITLE
Make Server Name Required

### ISSUE THREAD

**Issue by llin1234** [ultrasonic/ultrasonic#301]
## Problem description

It's possible to save a server without entering a name. It'll test ok but won't be listed in the Select Server dropdown.

### Steps to reproduce
Add Server
Leave Name blank
Complete Server Address
Return to UltraSonic Main
Tap Select Server

## System information

 * **Ultrasonic version**: 2.11.2

**Comment by ogarcia** [comment]
Duplicate #217
