### ISSUE TITLE
On the SelectArtistActivity, the Select Folder item doesn't work

### ISSUE THREAD

**Issue by nitehu** [ultrasonic/ultrasonic#305]
## Problem description

On the SelectArtistActivity, the Select Folder item doesn't work after #300.

### Steps to reproduce

- Install Ultrasonic version before #300 
- Go to Ultrasonic Main -> Artist
- Click Select Folder
- Select Folder context menu appears
- Install Ultrasonic version after #300 
- Go to Ultrasonic Main -> Artist
- Click Select Folder
- Nothing happens

## Additional notes

It seems the index of this item has changed from 1 to 0. There are a few checks which test for "1", these should be changed to "0".

**Comment by ogarcia** [comment]
Change to _"0"_ fix the menu display, but you cannot select any option, always goes back to _"All folders"_.

**Comment by nitehu** [comment]
Yes because there is another `else if (info.position == 1)` in `onContextItemSelected` :)

**Comment by ogarcia** [comment]
Yes! Change both seems fix the issue :slightly_smiling_face:
