### ISSUE TITLE
Drop menudrawer an use NavigationUI

### ISSUE THREAD

**Issue by ogarcia** [ultrasonic/ultrasonic#310]
## Problem description

Current menudrawer is legacy code that can cause problems in future. It must be replaced with [NavigationUI](https://developer.android.com/guide/navigation/navigation-ui)

**Comment by fkrivsky** [comment]
Will this one perhaps address also https://github.com/ultrasonic/ultrasonic/issues/165 ?

**Comment by Maxmystere** [comment]
Should the update replace all activites with fragments to comply better with NavigationUI
I've started tinkering with it and it seems like a lot of update

**Comment by nitehu** [comment]
Yep I've also checked this before, and it seems to be a decent amount of refactor to do it properly.
I'm not sure yet if it can be done in smaller steps...

**Comment by Maxmystere** [comment]
Would be a good time to replace all java with kotlin but will be a lot of work and might invalidate other PR if merged while other features are worked on

**Comment by ogarcia** [comment]
We can _close_ all other features and only work on this one. What do you think?

In the past we have a similar situation and can do the same: https://github.com/ultrasonic/ultrasonic/commit/e94e39e6d11e2bdf2283ce822c44119e631959e2

**Comment by Maxmystere** [comment]
This would be a really good idea

**Comment by nitehu** [comment]
I agree, it is better if we don't try to merge something else during a bigger refactor (not that there are that much PRs usually...)
Also I think this issue should focus on refactoring to NavigationUI, and change to Kotlin only those classes which would benefit from that (other kotlin migration can be done gradually, without extending the scope of this issue).

**Comment by ogarcia** [comment]
Done. I'll close 2.17.x and publish new 2.18.0 with the [pending changes in develop](https://github.com/ultrasonic/ultrasonic/milestone/13?closed=1) to have workspace clean

Update: 2.18.0 published
