### ISSUE TITLE
[Feature Request] Dark Theme (Black Amoled)

### ISSUE THREAD

**Issue by awsms** [ultrasonic/ultrasonic#317]
Hi, I wanted to know if you were planning to add a completely black theme at some point?
Thanks for all the great work on this app btw!

**Comment by awsms** [comment]
Any chance you could also add a _true black_ mode, like [this](https://i.imgur.com/Ehhzjmr.png)?

**Comment by awsms** [comment]
Any chance you could also add a _true black_ mode, like [this](https://i.imgur.com/Ehhzjmr.png)?

Not that I dislike this current black/cyan theme, which looks really neat! But I was specifically a looking for a black amoled mode :-)

**Comment by ogarcia** [comment]
@awsms the black theme is based in `Theme.MaterialComponents`. Is the one that [Google recommends to OLED Screens][1] (see second paragraph).

[1]: https://material.io/develop/android/theming/dark
