### ISSUE TITLE
Issues Connecting With Latest Airsonic Advanced

### ISSUE THREAD

**Issue by seniorm0ment** [ultrasonic/ultrasonic#319]
Having issues connecting after migrating from Airsonic to the latest Airsonic Advanced release it seems.

Not at my computer so I can't grab version information off hand.

**Comment by awsms** [comment]
Ultrasonic is working fine here with the build "Edge Release 11.0.0-SNAPSHOT.20201002122917"

**Comment by ogarcia** [comment]
@grravity We need more info. No known issues with Airsonic. What version of Ultrasonic? What error? What are you doing?

**Comment by awsms** [comment]
> @grravity We need more info. No known issues with Airsonic. What version of Ultrasonic? What error? What are you doing?

He's talking about [airsonic-advanced](https://github.com/airsonic-advanced/airsonic-advanced), a fork of Airsonic.

**Comment by seniorm0ment** [comment]
Sorry I've been busy, I'll grab the versions tomorrow.
And yes that fork

**Comment by seniorm0ment** [comment]
I can't even get on my airsonic server, I think the db might be corrupt. I don't remember that being the case when I originally made this issue but I could be wrong.
Idk that could be the issue for this.
I think I might just go back to Jellyfin for music.

**Comment by ogarcia** [comment]
Tested [Airsonic-Advanced][1] with latest [edge release][2] and works without problem.

[1]: https://github.com/airsonic-advanced/airsonic-advanced
[2]: https://github.com/airsonic-advanced/airsonic-advanced/releases/tag/11.0.0-SNAPSHOT.20201007202626
