### ISSUE TITLE
[Question] About the playback behaviour

### ISSUE THREAD

**Issue by awsms** [ultrasonic/ultrasonic#322]
I wanted to know if Ultrasonic will first completely cache a song before playing it, or if it can seek on the go, such as the webUI can for example.
I'm asking this because it can take a considerable amount of time to transcode a +50minutes FLAC file.

**Comment by ogarcia** [comment]
Transcoding is done on the server. Ultrasonic does not perform any about that. If the server takes five minutes to finish transcode, you must wait one or two minutes to have a minimal part of file to play it.

Anyway Ultrasonic start to play files when have a piece that can read. Don't need download full file. You can test this adding a big mp3 file to your server and play it without donload first.
