### ISSUE TITLE
"Play all" makes previously played album to be played again

### ISSUE THREAD

**Issue by etiennebaque** [ultrasonic/ultrasonic#323]
## Problem description

When pressing "Play all" for one album, this album will start playing. Then pressing "Play all" then for a second album will trigger the first album to play, not the second one.

### Steps to reproduce

1. Select an album, press "Play all" button (ie. top right "Play" button).
2. After album starts playing, press stop, close the app (or put phone on sleep).
3. Go back to the app, it reopens on the first album that was playing. Press back a few times to browse to a second album. 
4. Press "Play all" button for that second album.

#### Expected result:

That second album starts playing from the beginning (ie. from track 1).

#### Actual result:

The first album starts playing again from beginning. We need then to press the (android os) back button, then press "Play all" another time for this second album to finally get it start playing.

## System information

 * **Ultrasonic version**: 2.12.0 (bug occurred on at least the two versions prior to that)
 * **Android version**: Android 8.0.0
 * **Device info**: LG G6

**Comment by ogarcia** [comment]
Seems that top right Play buttom don't clear current playlist and add the album to bottom of current list

**Comment by etiennebaque** [comment]
> Seems that top right Play buttom don't clear current playlist and add the album to bottom of current list

Thanks for your comment @ogarcia. I was wondering today about this: if the second album was added at the bottom of the current list, why would a second press on that "Play all" button actually play that album?

To be consistent with the behaviour you're describing, on second press of that "Play all" button, the second album about added again at the bottom of the playlist and the first album would keep playing. What do you think?

**Comment by ogarcia** [comment]
@etiennebaque is a bug, the _play all_ button must clean the list. For add to queue there is two buttons, one to add next and other to add to bottom.
