### ISSUE TITLE
Improve offline mode

### ISSUE THREAD

**Issue by ogarcia** [ultrasonic/ultrasonic#324]
## Problem description

Now the offline mode is very basic. If an artist has not albums appear because folder exists. The same occurs with empty albums. We must improve offline mode to avoid this behaviour.

In the other hand, a delete option is missing in album or in artist. You can select songs to delete one by one, but you cannot delete an entire album or an artist.

And finally, we have a bug with current delete song. After press delete button, the song is deleted well, but the list don't refresh and the app does not seem do nothing. I think that this bug can be solved checking if the user is in offline mode and removing element from list after pressing delete button.

**Comment by eddyizm** [comment]
I'm having a hard time even finding the offline mode or offline files.

**Comment by tzugen** [comment]
I would suggest that offline mode is a status of the selected server, and not a "server" itself.
It would be nice if it would cache the metadata of the downloaded albums as well, so that you list like "Recently added albums" as well.

**Comment by tzugen** [comment]
With #445 merged, we could now save the Entitys of each Album etc, that the user downloads into the offline database.
Then, when offline, we can use the database to get nice views.

**Comment by ogarcia** [comment]
Related with #718
