### ISSUE TITLE
Unable to connect to Nextcloud/Subsonic server

### ISSUE THREAD

**Issue by oblivionnewtonjohn** [ultrasonic/ultrasonic#327]
## Problem description

Unable to connect to Nextcloud/Subsonic server with URL and credentials

### Steps to reproduce

Describe how somebody else could observe the same behavior you do. Don't share here any logins and 
passwords!

## System information

 * **Ultrasonic version**: *Version 2.12.0*
 * **Android version**: *9*
 * **Device info**: *Moto E6*

## Additional notes

Include any extra notes here. Otherwise you may remove this section.

**Comment by ogarcia** [comment]
Can you provide more information? What error? What see on your server? Are you using http or https?

**Comment by oblivionnewtonjohn** [comment]
Hi Oscar,

Apparently I missed this and need to perform beforehand:
owncloud/music: Music app for ownCloud (github.com)<https://github.com/owncloud/music#ampache-and-subsonic>

I will let you know if the issue persist after trying the above.

Spence

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by oblivionnewtonjohn** [comment]
I got it configured and working correctly.
Thanks for the prompt response.

Spence

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Spencer Crawford<mailto:spence.crawford@outlook.com>
Sent: Tuesday, October 6, 2020 3:30 PM
To: ultrasonic/ultrasonic<mailto:reply@reply.github.com>; ultrasonic/ultrasonic<mailto:ultrasonic@noreply.github.com>
Cc: oblivionnewtonjohn<mailto:oblvnnwtnjhn@gmail.com>; Author<mailto:author@noreply.github.com>
Subject: RE: [ultrasonic/ultrasonic] Unable to connect to Nextcloud/Subsonic server (#327)

Hi Oscar,

Apparently I missed this and need to perform beforehand:
owncloud/music: Music app for ownCloud (github.com)<https://github.com/owncloud/music#ampache-and-subsonic>

I will let you know if the issue persist after trying the above.

Spence

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
