### ISSUE TITLE
gPodder plugin ?

### ISSUE THREAD

**Issue by JOduMonT** [ultrasonic/ultrasonic#330]
Ultrasonic rock;

> I cross open this Feature Request at [Airsonic](https://github.com/airsonic/airsonic/issues/1811), [Audinaut](https://github.com/nvllsvm/Audinaut/issues/97), [Clementine](https://github.com/clementine-player/Clementine/issues/6811), and [Ultrasonic](https://github.com/ultrasonic/ultrasonic/issues/330) with hope of collaboration.

I start using it for my music, then I realize I could centralise my podcast too.
While on my Android, I'm juggling, between Subsonic, Audinaut, Ultrasonic and AntennaPod
and on my Laptop using Clementine

I still see a place for improvement
- **Ultrasonic** support podcast but, it is slowish and unstable/don't work while I try to use is for video. It also misses function like Recently added, Top rated and so on we could find in Subsonic. I was using it for my podcast, but I transferred to AntennaPod.

Sadly, I'm not technical enough to understand and see what/if it is possible but

- if Ultrasonic was an option to sync with gPodder it would love it more

**Comment by ogarcia** [comment]
Duplicated of #45
