### ISSUE TITLE
screen with incremental search of whole library

### ISSUE THREAD

**Issue by quite** [ultrasonic/ultrasonic#331]
I wish there was an (maybe optional) main screen with incremental search of the whole library, filtering on artist, album names (possibly even songs).

**Comment by awsms** [comment]
Would love to see this on Ultrasonic. This feature is on DSub, so it's definitely doable here too.

**Comment by ogarcia** [comment]
You have an option into menu for search that looks in whole library and make groups by Artists, Albums and songs. Can you detail more your feature request? (With screenshots or paintings better)

**Comment by awsms** [comment]
@ogarcia That's how it looks in DSub.
It searches in tags (trackname, artist(s), albumname), and foldernames.
![](https://i.imgur.com/BxkM8cz.png)

**Comment by quite** [comment]
I've tried out the Search screen a bit more now. I'm still missing an incremental search -- which would eliminate the need to hit Enter on the keyboard, or the "Click to search" button.

After adding songs, or visiting the Now playing screen, it is possible to get back to the Search screen by tapping back-button. That is good. Would still be nice to have it as a Main screen.

**Comment by ogarcia** [comment]
Incremental search implies send queries to server in every key press that is inefficient in this contex. Closing for now.

**Comment by quite** [comment]
On 6 November 2020 18:48:36 CET, "Óscar García Amor" <notifications@github.com> wrote:
>Incremental search implies send queries to server in every key press that is inefficient in this contex. Closing for now.
>

You'd of course only search when user have (at any moment) typed an amount of characters and made a brief pause. As well a minimum number of chars. There is a lot of ux patterns for this, i believe. But, anyway...
