### ISSUE TITLE
Support only partial download of a file for buffering 

### ISSUE THREAD

**Issue by etcimon** [ultrasonic/ultrasonic#334]
Hello,

Basically there is no way to stop music preloading for mobile so that it buffers the "buffer seconds" setting, so when I skip songs it downloads them all on mobile and this uses an incredible amount of bandwidth.

**Comment by etcimon** [comment]
You can obtain the desired effect by using a buffer of 1 second, proxying through nginx, transcoding to mp3 320kbps (for the bandwidth limit to be just right for all tracks) and setting the following config options in nginx:

```
        limit_rate_after 300k; # this will load the first 300kb of the track to start playback quickly at first
        limit_rate       42k; #this will always keep a small forward buffer of the currently playing track
```

I'm expecting ultrasonic to do this with a 0 preloaded song settings and its "# seconds" buffer. Currently the "# seconds" buffer duration is used as a minimum download size ultrasonic requires before starting playback, while I would expect it to be converted to the size of media file that is to be preloaded / buffered for bandwidth limiting. E.g. a 10 second buffer would adjust the downloader to always preload the next 10 seconds of media file (for 320kbit/s mp3 that would be the next 400KB)

Also, it seems like the `maxBufferSize` is not observed by navidrome anymore, but a constant transcoding configuration must instead be selected for the player name in the web console.

**Comment by etcimon** [comment]
Couldn't get this working reliably without transcoding to libvorbis/webm. MP3 initial buffer can be 3MB or not even work for some reason

**Comment by nitehu** [comment]
As you've noticed, Ultrasonic's first priority currently is that you can listen to your songs as soon and as smoothly as possible, so it preloads the songs from your playlist, and only starts playing a song after a predetermined part of it is available. The size of this part can be adjusted with the "Buffer length" setting. 

Ultrasonic is not a "streaming" player in that sense it doesn't really support playing only a part of a very big (or endless) music stream, it downloads files from your collection and plays them back. For example, when you seek in a big file, it doesn't really jumps over those parts you skipped, just waits for them to be downloaded.

This can lead to the problem you've described, namely that if you only listen to the first few seconds of a song and then skip it, the file still will be downloaded, which can result in unnecessary mobile data usage.
One solution to this would be what you suggest, that Ultrasonic should only download a (configurable) part of a file and not the whole. This would also result in possibly reduced user experience if/when the buffer runs out, and in case of seeking in a file.

**Comment by etcimon** [comment]
The fact that ultrasonic is designed for Android is sufficient for most people to expect it to be a streaming software. Like I said, using vorbis/webm with bandwidth limits are the only things that allow me to play music on 4G (and soon 5G) without using up all my allocated data.

**Comment by ogarcia** [comment]
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
