### ISSUE TITLE
Problem entering new server info

### ISSUE THREAD

**Issue by thagoat** [ultrasonic/ultrasonic#341]
When entering information for a a new server, if your Android switched from landscape or portrait mode to the opposite mode all the info already entered is deleted and you have to re-enter all the information again. Only tested on the current 2.15.0 version of the app. Android 10, Motorola G7.

Also, coincidentally, when I upgraded to this version my currently loaded playlist was also removed; losing my spot in a playlist with over 2100 songs :cry:

**Comment by nitehu** [comment]
Thank you for reporting this! I'll create a fix.

Sorry for the lost playlist, I know the pain of scrolling through hundreds of songs... There were some refactoring lately which changed the structure of the saved internal state which may caused this. Also this is expected when you change servers I think.

**Comment by ogarcia** [comment]
But, the playlist issue has no sense with the change. The playlists are stored in server, if the server is the same you must have your playlist in it.

**Comment by thagoat** [comment]
Awesome thank you!
Also a small UI request; is there a way to make the media control buttons on the shade panel bigger? I find more than half the time, when I press the 'next' button it tries to open the app and I have to press back and then enlarge the widget again and try again. Not so safe when driving =)

**Comment by nitehu** [comment]
@ogarcia I think he didn't lose the playlist itself, just the current play position in it (the "Now Playing" list, or how is it called :). 
@thagoat I'll create a separate issue for the icon sizes.

**Comment by thagoat** [comment]
Correct, I did not lose the playlist. It just wasn't loaded anymore. Poof! lol
@nitehu Super, thank you very much!
