### ISSUE TITLE
Notification control icons should be bigger

### ISSUE THREAD

**Issue by nitehu** [ultrasonic/ultrasonic#342]
## Problem description

The control icons in the notifications are too small, sometimes it is hard to touch the one the user wants. They should be bigger, or there should be more padding / margin between them. It is especially noticeable on the small notification.

## Additional notes

As I know this (or a similar problem) was fixed before, but it seems the new vector icons are smaller than the previous ones, and that causes this problem again.

**Comment by Maxmystere** [comment]
Should we also add a different notification system for devices running Android 11 ?
https://developer.android.com/guide/topics/media/media-controls

**Comment by nitehu** [comment]
That seems to be a good idea, or at least something that is worth investigating (in a separate issue). 
There may be some problems however if Android11 is targeted, if I remember correctly there are some changes (again) regarding the storage access APIs.
Also, implementing a MediaBrowserService is useful for Android Auto too, for which support was requested before.
