### ISSUE TITLE
Increase media_buttons size

### ISSUE THREAD

**Issue by metalheim** [ultrasonic/ultrasonic#344]
## Problem description
The media buttons are very small on my device.
I would like the media buttons (epescially media_play / pause) to be displayed bigger, similar to the way f.e. spotifiy is displaying it.

Imho, these are the most used control and the are are mesely 5% of screen height, making them hard to access.

The play button in ultrasonic is ~96px height, while f.e. in spotify, it is 172px high (values for my device) and more prominently spaced.

![Screenshot (04 11 2020 14_21_23)](https://user-images.githubusercontent.com/44159957/98117637-5a1c2680-1eaa-11eb-84dd-1f79629e2942.jpg)

![Screenshot (04 11 2020 14_31_38)](https://user-images.githubusercontent.com/44159957/98117916-b0896500-1eaa-11eb-8c39-74a488e299e8.jpg)

## Additional notes

If nescecary, the cover-display size could be traded for that. It is very big anyway.

## System information

 * **Ultrasonic version**: *2.15.0*
 * **Android version**: *11*, RP1A.201005.004
 * **Device info**: *Google, Pixel 2*

BTW. Thank you all very much for this app, its a real joy to see a great app with active developers!

**Comment by nitehu** [comment]
This and #342 are caused by the new vector icons, they are smaller than the old, pixel based ones. Probably can be fixed together.

**Comment by ogarcia** [comment]
I think that simply setting the `media_buttons` layout must fix the problem

**Comment by metalheim** [comment]
Thanks, looks much better now!
