### ISSUE TITLE
"Invalid URL" when trying to use HTTP basic auth

### ISSUE THREAD

**Issue by andrewmichaelsmith** [ultrasonic/ultrasonic#351]
## Problem description

I have a Subsonic API that uses normal auth and HTTP basic auth on top of the Subsonic auth. 

FWIW this is navidrome with nginx in front of it. I have a user account set up on navidrome and nginx basuc auth http.

I believe it should be possible to do this "double authentication" (with nginx and navidrome) but when I try and enter the following a URL of the form `https://user:password@host.com` I get the error `Please specify a valid URL`.

### Steps to reproduce

Try and add a Server with URL `https://user:password@host.com`

## System information

 * **Ultrasonic version**: 2.15.0
 * **Android version**: 10
 * **Device info**: NA

## Additional notes

It's possible I've misunderstood something here - but looking at the API for the web browser client I user it looks like this should work (i.e. the double auth).

**Comment by nitehu** [comment]
Yes that's correct, currently Ultrasonic checks directly that the URL of the server shouldn't contain the "@" character. I'm not sure why though - as you wrote, "@" is valid if you have this double auth. Maybe it breaks something else, or maybe the double auth is so strange an idea that the original authors didn't think anyone would use it, and the "@" in the URL must be a mistake.

**Comment by ogarcia** [comment]
The only thing that we can do is build a similar setup, remove the filter and try. For me has no sense have double auth, but this may be transparent to app since the "user:password@" is managed by http client and server. I can do this along this week.

**Comment by andrewmichaelsmith** [comment]
Thanks! I am very happy to test (if you're able to send an apk).

**Comment by andrewmichaelsmith** [comment]
Ah OK, FWIW I tried the following change, which let me set the server but gives me a network error.

```
diff --git a/ultrasonic/src/main/kotlin/org/moire/ultrasonic/activity/EditServerActivity.kt b/ultrasonic/src/main/kotlin/org/moire/ultrasonic/activity/EditServerActivity.kt
index 7641afe3..2ab9e9cf 100644
--- a/ultrasonic/src/main/kotlin/org/moire/ultrasonic/activity/EditServerActivity.kt
+++ b/ultrasonic/src/main/kotlin/org/moire/ultrasonic/activity/EditServerActivity.kt
@@ -236,7 +236,6 @@ internal class EditServerActivity : AppCompatActivity() {
                 url = URL(urlString)
                 if (
                     urlString != urlString.trim(' ') ||
-                    urlString.contains("@") ||
                     url.host.isNullOrBlank()
                 ) {
                     throw MalformedURLException()
```

**Comment by andrewmichaelsmith** [comment]
(Deleted less relevant comment)

I did a bit of tinkering and was able to get it *working* (client worked against my backend with "double auth") with this code: https://github.com/andrewmichaelsmith/ultrasonic/pull/1/files**

It seems OkHTTP isn't that clever - we need to tell it to auth and need to give it the username and password. So need to parse it from the URL.

_Caveat_: I've hard-coded username/password for HTTP basic auth, wasn't immediately obvious how to poke this through (I am not familiar with kotlin).

**Comment by ogarcia** [comment]
So, the test has done. I deassing myself because don't have time this week to see how do the URL parse.

**Comment by Patricol** [comment]
I'd suggest supporting basic auth directly if possible; many other apps for selfhosted services (that have their own regular authentication schemes themselves) support that.

The basic thinking is that you can host the service behind completely bulletproof authentication and have absolutely zero concerns about vulnerabilities in airsonic etc.

And it can be done without inconvenience. Basic auth is inconvenient; but exposing Airsonic behind transparent SSO for web-browser usage and basic-auth for app usage gives all the security with no extra per-visit steps.
