### ISSUE TITLE
Cannot download videos to local cache, only songs

### ISSUE THREAD

**Issue by Rudd-O** [ultrasonic/ultrasonic#359]
## Problem description

When I ask a playlist that contains videos to be downloaded (long-press on the playlist), only the audio songs are downloaded.  The videos are not transcoded and downloaded, or even flat out downloaded as-is.

I would expect the videos to be downloadable as audio files, as Audinaut does when you ask Audinaut to cache a playlist.

The playlist view also doesn't show the same details for videos that it shows for regular songs.  Nor can playlists with videos be played normally with the Play button at the top — only the audio songs play then.

To be clear: tapping on the video results in the video opening with the video player and working correctly.  But I don't want to do this when I'm on the go, and I also don't want to save the whole video on my phone (limited storage).

### Steps to reproduce

Go to Playlist view on your Airsonic server within the app.  Select a playlist that contains videos.  Push for a while.  Select "Download".

## System information

 * **Ultrasonic version**: *latest F-Droid*
 * **Android version**: *11*
 * **Device info**: *Pixel 4*

**Comment by nitehu** [comment]
Thanks for creating this, I've completely forgot about it.
Anyways, I've checked and currently video playback really works as mentioned [here](https://github.com/ultrasonic/ultrasonic/issues/241#issuecomment-459463869), Ultrasonic just passes the video url to an external player. 
I'm not sure why, maybe video handling is still an incomplete feature.

**Comment by ogarcia** [comment]
Ultrasonic is centered to music play, so video features are delegated in external player (MX Player). Maybe the only enhancement here is that you can choose the video player that you like.

**Comment by Rudd-O** [comment]
Yes, I agree, Ultrasonic is centered around music playback, and that's awesome.

Therefore, video songs *should be downloaded as transcoded¹ to audio by the server*, rather than just having their stream URLs passed to an external app.  Of course, if people want the behavior of passing the stream URL for a video to an external app — in my view, a strange behavior for a self-described *music playing app* — there should be a setting to enable that (maybe even defaulting to on).

For the record, Audinaut does exactly that (unless the user explicitly wants to stream _the video_) and it's the right thing to do.  I can play playlists of videos and they all play as songs.  I can cache those videos and they get cached as audio.  It's great!

¹ Most Subsonic servers have inbuilt transcoding capabilities (in my case, it's Airsonic), so it's not at all difficult to get playlists of videos to play as a plain old music playlist.

**Comment by Rudd-O** [comment]
Hello, any activity on this?  Us music enthusiasts who want to be able to load our videos as songs on our phone would like to know.
