### ISSUE TITLE
Support for switching / selecting Media Folders

### ISSUE THREAD

**Issue by nroach44** [ultrasonic/ultrasonic#367]
## Problem description

Airsonic supports having separate folders of music "media folders" and then also supports limiting user accounts to certain folders. This allows us to keep distinct collections separate, while keeping them in the same system.

![image](https://user-images.githubusercontent.com/518487/103260578-12f97000-49d9-11eb-9b18-7727c54f5f91.png)
See on the left where the web UI allows me to pick which collection I'm browsing at the time, and on the bottom right showing how it's configured.

This addition would allow me to pick which collection I wish to browse/see in the app on the go, rather than seeing everything at once, or limiting the user account at the server level.

### Steps to reproduce

N/A

## System information

 * **Ultrasonic version**: 2.17.2
 * **Android version**: Android 10
 * **Device info**: N/A (Any)

**Comment by ogarcia** [comment]
This behaviour is already present in Ultrasonic, when you go to Music -> Artists the first element of list is a folder selector

**Comment by nroach44** [comment]
@ogarcia It's not if you have browsing by tag selected, and even with it turned off, it doesn't offer you the _selection_ of which set of "media folders" (not normal folders) to use. Note that the above "media folders" are handled differently from folders within the library.

Please try adding another "Media Folder" yourself and testing it out.

**Comment by nroach44** [comment]
This is what I see, with browse by tags off, and with a user account that has two **media folders** enabled. There is no selection to pick between them
![Screenshot_20201229-161652_Ultrasonic](https://user-images.githubusercontent.com/518487/103269904-c1111400-49f1-11eb-876b-154ac0d36350.png)

**Comment by ogarcia** [comment]
If you enable _browse by tags_ you don't have folder list because API don't support it :disappointed:  (is a different API request). If you disable the option you must see something like this:

![utrasonic_artist_list_2020-12-29_09-56-24](https://user-images.githubusercontent.com/572924/103272106-4679d180-49bc-11eb-90a7-f5dc7a19c5db.jpg)

The first element of list (_Seleccionar la carpeta_ in my case because I have te app in Spanish) is the _folder selector_.

**Comment by nroach44** [comment]
@ogarcia Ah right, I managed to turn off the right setting (Browse by ID3 tags, rather than one of the other ones I thought was doing it) and it shows. Would it be possible to get it at a more high-level (something like under the server selector on the main page)?

**Comment by ogarcia** [comment]
> Would it be possible to get it at a more high-level (something like under the server selector on the main page)?

No, because it depends of API responses.
