### ISSUE TITLE
Empty id in getCoverArt

### ISSUE THREAD

**Issue by ghuehl** [ultrasonic/ultrasonic#368]
## sharing of playlists doesn't work

Trying to share an existing playlist shows an error "requested data not found"

### Steps to reproduce

See above.

## System information

 * **Ultrasonic version**: 2.17.2
 * **Android version**: 8.0.0
 * **Device info**: HUAWEI MediaPad M5 lite

**Comment by nitehu** [comment]
Sharing existing playlists works for me on Amapche and Airsonic.

The "Requested data was not found" error is returned by the server, and I'm not sure why yet.
Could you please include what kind of server (and which version of it) do you use?
It would also really help if you could add some debug logs of your server communication.

**Comment by ghuehl** [comment]
Here's the log... hope it's useful.

[PHP] Error: Error: Undefined offset: 1 at /var/www/nextcloud/apps/music/controller/subsoniccontroller.php#370 at <<closure>>

0. /var/www/nextcloud/apps/music/controller/subsoniccontroller.php line 370
   OC\Log\ErrorHandler::onError(8, "Undefined offset: 1", "/var/www/nextcl ... p", 370, {id: "",size: nu ... "})
1. /var/www/nextcloud/apps/music/controller/subsoniccontroller.php line 148
   OCA\Music\Controller\SubsonicController->getCoverArt()
2. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 169
   OCA\Music\Controller\SubsonicController->handleRequest("getCoverArt")
3. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Music\Contro ... {}, "handleRequest")
4. /var/www/nextcloud/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Music\Contro ... {}, "handleRequest")
5. /var/www/nextcloud/lib/private/Route/Router.php line 308
   OC\AppFramework\App::main("SubsonicController", "handleRequest", OC\AppFramework\ ... {}, {action: null,me ... "})
6. /var/www/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/music/sub ... w")
7. /var/www/nextcloud/index.php line 37
   OC::handleRequest()

GET /index.php/apps/music/subsonic/rest/getCoverArt.view?id=&u=ncp&c=Ultrasonic&f=json&v=1.11.0&p=enc:667431317839636568763666
from 192.168.178.124 at 2021-01-14T21:34:21+00:00

**Comment by ogarcia** [comment]
You must report this bug to server developer because is a problem in server app. Not is a bug itself, simply that don't handle an empty ID value.

In the other hand, you must have a problem with your database because Ultrasonic is sending an empty ID:
```
/index.php/apps/music/subsonic/rest/getCoverArt.view?id=&u=ncp...
```
Do you refresh the list before try sharing?

**Comment by nitehu** [comment]
Also, Ultrasonic usually doesn't send empty id values in getCoverArt, please check the "Enable new image loader" setting at the end of the settings screen. Try to disable that and see if that fixes the problem as a temporal solution.

If that helps, maybe we can extend the checks for empty ids in Ultrasonic just to be more compatible with the servers...

**Comment by ghuehl** [comment]
Okay, I've tried - same error occurs. But it doesn't matter. I like
Ultrasonic very much. Thanks to all and your support.

Am Fr., 15. Jan. 2021 um 09:16 Uhr schrieb Nite <notifications@github.com>:
