### ISSUE TITLE
Crash when viewing by genres

### ISSUE THREAD

**Issue by tomleb** [ultrasonic/ultrasonic#371]
## Problem description

The app crashes when trying to list the music by genres.

### Steps to reproduce

Able to reproduce 100% times:

1. Open the app
2. Click on **Genres** under **Music**
3. App crashes

## System information

 * **Ultrasonic version**: *2.17.2*
 * **Android version**: *Android 8.1.0*
 * **Device info**: *Xiami, Mi A2*

## Additional notes

Here is the [ultrasonic-stacktrace.txt] file that's being dumped on the phone when it crashes.

I am using Navidrome as the server. I can see the request coming in and it is returning a 200.

[ultrasonic-stacktrace.txt]: https://paste.sr.ht/blob/239a14c36c8bfa34f1f0df57b64dfc00b1ef274a

Edit:

Here is what Navidrome is sending:

```json
{
  "subsonic-response": {
    "status": "ok",
    "version": "1.16.1",
    "type": "navidrome",
    "serverVersion": "0.39.0 (f2a8308)",
    "genres": {
      "genre": [
        {
          "value": "<Empty>",
          "songCount": 303,
          "albumCount": 63
        },
        {
          "value": "Alternative Rock, Pop Punk, J-Rock",
          "songCount": 5,
          "albumCount": 1
        },
       ...
      ]
    }
  }
}
```

**Comment by nitehu** [comment]
Sorry this is my bad, I thought I've fixed these kind of bugs already. It is because I've changed the layout for artist list items and that same layout was still used elsewhere.
