### ISSUE TITLE
Change left-arrow to hamburger menu

### ISSUE THREAD

**Issue by tomleb** [ultrasonic/ultrasonic#372]
# UI Suggestion

I propose changing the left-arrow icon (in the top left corner) to an hamburger menu. I always get confused because I expect left-arrow to bring me to previous screen but instead it opens up the navigation drawer. The behavior is fine but I think it would be easier to understand with an hamburger menu instead of the left-arrow icon.

What do you think?

**Comment by nitehu** [comment]
Thank you for this suggestion!
However, I think this will be fixed in #310 anyways, and maybe it isn't necessary to replace only the icon before refactoring the navigation.

**Comment by tomleb** [comment]
Interesting. Has the migration work started ? I can live with the left-arrow for sure. If the navigation work takes a while it might be worth changing the icon since it's a tiny change. Your call :)

**Comment by ogarcia** [comment]
We can close this issue and handle comments in #310 :wink:
