### ISSUE TITLE
App crashes when scrolling through albums

### ISSUE THREAD

**Issue by tomleb** [ultrasonic/ultrasonic#380]
## Problem description

The app crashes when I scroll through the albums and go to the ~2-3 first pages. Note that I use the new image loader and I display 25 albums per page.

### Steps to reproduce

1. Open the app
2. Open the list of albums
3. Scroll down to get the next page button
4. Click on next page button to go to the next page
5. Repeat steps 3-4 a few times (3 times is enough)
6. App crashes

## System information

 * **Ultrasonic version**: *2.17.2*
 * **Android version**: *Android 8.1.0*
 * **Device info**: *Xiami, Mi A2*

## Additional notes

Here is the [ultrasonic-stacktrace.txt] file that's being dumped on the phone when it crashes.

[ultrasonic-stacktrace.txt]: https://paste.sr.ht/~tomleb/480b5fc4252856ff0b952b3a0f683061a7de746e

I have tested without the new image loader and it does not crash.

Unrelated, but when can we see 2.17.3 released on F-Droid?

**Comment by nitehu** [comment]
Wow, it seems Ultrasonic tried to load a ~156MB album art 😳
I think it should instead try to ask for a resized image, or detect and ignore large files like that...

**Comment by ogarcia** [comment]
> Unrelated, but when can we see 2.17.3 released on F-Droid?

We cannot control F-Droid updates, is an [automagical proccess](https://f-droid.org/es/docs/FAQ_-_App_Developers/#do-i-need-to-tell-you-when-i-update). As I can see, the version [2.17.3](https://f-droid.org/wiki/page/org.moire.ultrasonic/lastbuild_87) and [2.18.0](https://f-droid.org/wiki/page/org.moire.ultrasonic/lastbuild_88) are both builded by F-Droid but not published. They are [working in a new version of server](https://mastodon.technology/@fdroidorg/105554596788821918), maybe can be related with this.
