### ISSUE TITLE
random songs-playlist doesnt get generated

### ISSUE THREAD

**Issue by fanyx** [ultrasonic/ultrasonic#381]
## Problem description

I host my own Funkwhale instance.
Kinda recently, Ultrasonic stopped generating a random playlist. Not the view from the sidebar menu, that one works. But if you press the "random" button in the Main view at the top right, nothing gets generated/called.
The API Call "getRandomSongs" works, tested with Jamstash on PC.

### Steps to reproduce

Don't really know how.
Error persists through reinstall.
I can assist in providing infrastructure to test

## System information

 * **Ultrasonic version**: *2.18.0 - F-Droid clean install*
 * **Android version**: *10*
 * **Device info**: *OnePlus 5, OxygenOS 10.0.1*

**Comment by ogarcia** [comment]
Please, look in the server logs for Ultrasonic call at moment that you press the random button and paste it here.

**Comment by fanyx** [comment]
The Server is a dockerized Installation of Funkwhale 1.0. Sadly it does not generate a log entry at all, even though the nginx registers an access with HTTP 200.

`172.20.0.2 - - [22/Mar/2021:09:11:01 +0000] "GET /rest/getUser.view?username=fanyx&u=fanyx&c=Ultrasonic&f=json&v=1.16.0&t=daa5d093e0f67f19e72b47e817308d21&s=A656B0E1F00A689F1E63E7E6CF2FCE37 HTTP/1.1" 200 434 "-" "okhttp/3.10.0" "83.135.155.109"`

The Ultrasonic log shows a serialization attempt on an empty set. I'll attach the part of the log that should be relevant to this error.
[ultrasonic.1.log](https://github.com/ultrasonic/ultrasonic/files/6180878/ultrasonic.1.log)

**Comment by ogarcia** [comment]
Ok. Send this request to your server and paste response. If your server is in `myserver.example.com` the request must be:
```
http://myserver.example.com/rest/getUser.view?username=fanyx&u=fanyx&c=Ultrasonic&f=json&v=1.16.0&t=daa5d093e0f67f19e72b47e817308d21&s=A656B0E1F00A689F1E63E7E6CF2FCE37
```

**Comment by fanyx** [comment]
Response is:

`{"subsonic-response":{"funkwhaleVersion":"1.1","status":"ok","type":"funkwhale","user":{"username":"fanyx","email":"fanyx@pm.me","scrobblingEnabled":"true","adminRole":"false","settingsRole":"false","commentRole":"false","podcastRole":"true","coverArtRole":"false","shareRole":"false","uploadRole":"true","downloadRole":"true","playlistRole":"true","streamRole":"true","jukeboxRole":"true","folder":[{"value":1}]},"version":"1.16.0"}}`

i hope the formatting is not too terrible...

**Comment by ogarcia** [comment]
The problem is located in your server. The folder entry in response is bad formatted. If you see [the sample](http://www.subsonic.org/pages/inc/api/examples/user_example_1.xml) in XML you can see that _"folder"_ has not _"value"_. The correct form in JSON is:
```json
{
   "@status": "ok",
   "@version": "1.12.0",
   "user": {
      "@username": "sindre",
      "@email": "sindre@activeobjects.no",
      "@scrobblingEnabled": "true",
      "@adminRole": "false",
      "@settingsRole": "true",
      "@downloadRole": "true",
      "@uploadRole": "false",
      "@playlistRole": "true",
      "@coverArtRole": "true",
      "@commentRole": "true",
      "@podcastRole": "true",
      "@streamRole": "true",
      "@jukeboxRole": "true",
      "@shareRole": "false",
      "folder": [
         "1",
         "3"
      ]
   }
}
```
I suggest you that open a new issue in Funkwhale.

**Comment by fanyx** [comment]
thank you for the information
i will forward this to the funkwhale team

**Comment by fanyx** [comment]
Still interested in fixing this.

I have reverted the Funkwhale version to an interation where this reponse formatting seemingly was not introduced yet. Now the response seems to be in correct subsonic-json. Can you confirm this or does the folder value also need to be in qutoes?

```
{
  "subsonic-response": {
    "status": "ok",
    "version": "1.16.0",
    "type": "funkwhale",
    "funkwhaleVersion": "0.20.1",
    "user": {
      "username": "fanyx",
      "email": "fanyx@pm.me",
      "scrobblingEnabled": "true",
      "adminRole": "false",
      "settingsRole": "false",
      "commentRole": "false",
      "podcastRole": "false",
      "coverArtRole": "false",
      "shareRole": "false",
      "uploadRole": "true",
      "downloadRole": "true",
      "playlistRole": "true",
      "streamRole": "true",
      "jukeboxRole": "true",
      "folder": [
        1
      ]
    }
  }
}
```

If this is correctly formatted, the error persists in Ultrasonic. If this, and this is what i assume, corrupted json, i will check back with the funkwhale-team. I only know that unquoted json values are rather uncommon.
