### ISSUE TITLE
Translations not up to date

### ISSUE THREAD

**Issue by RomainTT** [ultrasonic/ultrasonic#385]
Hi !
I’m a contributor on Transifex, and I did not find a better way than this issue to bring to your attention that many translations are available and not merged yet. Is it possible to do it now ?

How often do you merge them ? Is there a better way to drag attention on new translations ?

Anyway, thank you for this app, it’s awesome.

**Comment by ogarcia** [comment]
Please, first do a double check in Transifex to see if the chain that you think that are translated are already done, and second if your tranlation is newer than latest version is normal that it is not merged since updating the translations is the last thing to do before publish a new release.

**Comment by RomainTT** [comment]
Ok thanks for your answer !
