### ISSUE TITLE
Current top left icon (🡨) is misleading (☰ would be better)

### ISSUE THREAD

**Issue by jerome-pouiller** [ultrasonic/ultrasonic#387]
Hello,

I use Ultrasonic for a while now, and I can't get used to the top left icon (a left arrow like this: 🡨). I would expect it come back to the previous screen but it open the main menu.

I think it would clearer if it was replaced with a menu icon (three horizontal bars: ☰)

**Comment by Maxmystere** [comment]
Will be fixed with pending pull request #382

**Comment by nitehu** [comment]
Yep, this will be fixed in the next release, thank you for the suggestion anyways!
