### ISSUE TITLE
Podcasts not loading on 2.19.1

### ISSUE THREAD

**Issue by ardydavari** [ultrasonic/ultrasonic#394]
## Problem description
Unable to load podcasts on latest release of ultrasonic app on f-droid.

### Steps to reproduce
No podcasts are displayed, I had to downgrade back to 2.18.0 to fix.

## System information

 * **Ultrasonic version**: 2.19.1
 * **Android version**: 11
 * **Device info**: Pixel 4a
 * Airsonic version: 10.6.2 (docker linuxserver)

**Comment by nitehu** [comment]
Thank you for reporting this!
It will be fixed in the next release.
