### ISSUE TITLE
"Next" button doesn't shift playback from the last to the first track of playlist when Repeat playlist is toggled

### ISSUE THREAD

**Issue by vadiof** [ultrasonic/ultrasonic#397]
When Repeat playlist option is toggled and the last track playing, it's impossible to shift to the first track(which is logically "next") with Next track button. Yet if track(and playlist) ends then playback automatically switches to the first track of playlist. There is some inconsistency in this behavior in my opinion and it would be nice to have this feature.
Thanks!

**Comment by nitehu** [comment]
Yes you're right, I also think this is a bug, the next song after the last should be the first if repeat all is turned on.
