### ISSUE TITLE
Show download percentage

### ISSUE THREAD

**Issue by tzugen** [ultrasonic/ultrasonic#403]
Hi there :)

I would like to start contributing to the project. To start to get familiar I thought of fixing a few small bugs that I expirienced personally.

I think that I would like to do is to change the way download progress is reported currently. Right now the UI displays the amoun of megabytes downloaded, while I think that it might be more helpful to show a percentage.

If you have ideas regarding this I would be happy to hear them.

**Comment by tzugen** [comment]
Also, is this related to #257 ?

**Comment by nitehu** [comment]
I also think the percentage display would be more helpful. For me, it usually disappears in a second, but for someone who downloads big files like podcasts this may be more informative.
#257 is about something else. The problem there was that Ultrasonic uses the "stream" api for downloading the songs, when there is actually a "download" api is available (the difference is that e.g. the server may transcode the files when they are streamed).
