### ISSUE TITLE
Cannot play any video

### ISSUE THREAD

**Issue by EricBrunel** [ultrasonic/ultrasonic#407]
## Problem description

Any attempt to play a video displays a message:
```
Calling startActivity() from outside
of an Activity context requires the
FLAG_ACTIVITY_NEW_TASK flag. Is this
really what you want?
```
The format of the video doesn't seem to matter: nothing I tried worked.

This used to work: playing a video file asked what player to open and the video was playing without problem. Audio files work fine, and videos do work with the "official" Subsonic app, so the problem does not seem to be on the server.

## System information

 * **Ultrasonic version**: 2.19.2
 * **Android version**: 10
 * **Device info**: Nokia 8.1

**Comment by qwertyuser1983** [comment]
Confirmed happen to mine phone too. 

Ultrasonic 2.19.2
Android 10
2 devices, Nokia 5.3, Advan G9 Pro

(｡•́︿•̀｡)
