### ISSUE TITLE
How do you enable/send to jukebox outside the server config?

### ISSUE THREAD

**Issue by lachlan-00** [ultrasonic/ultrasonic#412]
I haven't seen an option to enable jukebox outside of the server config.

Is it possible to turn it on/off or "send to jukebox" from a menu? (Like for a playlist, album/track)

If not, I've configured a forced localplay server which seems like an easy way to handle it.

**Comment by nitehu** [comment]
On the Now Playing screen, there is an options menu, where jukebox can be enabled and disabled (Jukebox On / Off). It sends and plays your current playlist on the server.
Now I didn't use this much just when testing, and the menu seems to be hidden for me at least when I use Ampache.
From the code it seems the menu is only enabled if the getUser.view request returns a user with "jukeboxRole" : true
With an Airsonic admin user, this just works out of the box.

**Comment by lachlan-00** [comment]
Ahh cool that might mean that I need to add that role to Ampache if it's missing.

Good to know, I'll investigate my server and check the roles are returned

**Comment by lachlan-00** [comment]
Confirming for anyone interested that it's hardcoded false for Ampache. Will be fixing that up asap tomorrow!
