### ISSUE TITLE
The "Starred" view never shows me anything

### ISSUE THREAD

**Issue by SaintDubious** [ultrasonic/ultrasonic#417]
## Problem description

Whenever I open up the "Starred" view I just get an empty screen with "no media found." I wonder if I just don't understand how starring is supposed to work. I've tried adding stars to both my albums and individual songs. Does anyone else see this issue?

### Steps to reproduce

Click on the little star icon next to albums or songs. Go to the "Starred" view.

## System information

 * **Ultrasonic version**: 2.18.0 (and develop branch on emulator)
 * **Android version**: 11 (and emulator)
 * **Device info**: Pixel 3

**Comment by nitehu** [comment]
I've just tried out with Airsonic, this may be a bug. Ultrasonic calls getStarred2.view, the server returns the albums that was starred, but Ultrasonic shows only an empty list...

Edit: I've made the stars work, it seems it shows only songs and not albums... 
I'm not really sure what is the expected behavior here, maybe it was more clear if the menu title would say "Starred songs" or the list would contain both.

**Comment by ogarcia** [comment]
In main screen you have two starred items, the first one under songs and the second one under albums. The first onle only list starred songs and the second one only list starred albums. This work well in 2.19.2 with Supysonic.
Warning: If you starred all songs in an album not is the same that if you starred the album.

**Comment by nitehu** [comment]
Ok so I've tested the following permutations:
- Browse using ID3 Enabled
  - Starred songs: Ultrasonic calls getStarred2.view, the list is OK
  - Starred albums: Ultrasonic calls getAlbumList2.view?type=starred, the list is OK
- Browse using ID3 Disabled
  - Starred songs: Ultrasonic calls getStarred.view, the list is OK
  - Starred albums: Ultrasonic calls getAlbumList.view?type=starred, the list is empty

This last one doesn't work with Airsonic latest, but the request is OK according to the Subsonic API, so it seems to be a server error.

@SaintDubious could you please try to verify these results if they are the same for you? If this isn't an Ultrasonic bug it can be closed.

**Comment by SaintDubious** [comment]
confirmed that this is a problem with ampache (my music server) and not ultrasonic. I used curl to send it the same requests ultrasonic does and they all come back with empty lists. Thanks for looking into it, sorry for the false bug.
