### ISSUE TITLE
Regression?

### ISSUE THREAD

**Issue by tzugen** [ultrasonic/ultrasonic#418]
## Problem description

Yesterday I had problems with unexpectedly stopping playback again. I couldn't look to deep into it yet, but it could have been a regression in LocalMediaPlayer or a an Adroid issue with MediaPlayer.  I won't have time to dig into it until the weekend, so it would be great if you didn't release a new version until then.

**Comment by tzugen** [comment]
Do you want to skip 2.19 or close it?
If you want to release 2.19, you should cherry-pick this commit, as it fixes this bug:
https://github.com/ultrasonic/ultrasonic/pull/421/commits/427c81acc16c99d7de06f057398d27b4cb908c5c

**Comment by ogarcia** [comment]
I think that better perform a new release 2.10.0 with all changes
