### ISSUE TITLE
HTTPS Certificate Error. Trust anchor for certification path not found with airsonic behind NGINX proxy

### ISSUE THREAD

**Issue by Ron-Olsthoorn** [ultrasonic/ultrasonic#427]
## Problem description

When trying to use ultrasonic i get the message as per the subject.  https/SSL terminates on the NGINX proxy before passing it on to airsonic advanced. Works fine when connecting to the non-http/non-proxied. Also works fine using the dsub client

## System information

 * **Ultrasonic version**:  2.18.0
 * **Android version**: 10
 * **Device info**: *Mi 9T Pro

## Additional notes

I checked the certificate which is still valid (Let's Encrypt)

**Comment by tzugen** [comment]
I am also using a Lets Encrypt certificate. It works fine in API 29. In API 19 it fails in the emulator

**Comment by nitehu** [comment]
Believe it or not, [DSub always accepts all certificates](https://github.com/daneren2005/Subsonic/blob/3d4675600f1c70f4c52f6ba800b2eacd62e80b00/app/src/main/java/github/daneren2005/dsub/service/RESTMusicService.java#L136), even invalid ones.  
The same behavior can be enabled in Ultrasonic in the server settings, with "Allow self-signed certificate".
However, this is a security risk! Please configure your server correctly.
See [if this helps](https://stackoverflow.com/questions/6825226/trust-anchor-not-found-for-android-ssl-connection).
