### ISSUE TITLE
Playback through app does not reliably update recents on server

### ISSUE THREAD

**Issue by AMoonRabbit** [ultrasonic/ultrasonic#430]
## Problem description

Using Ultrasonic with my Funkwhale server via the Subsonic key. Enabled the scrobbling option as I noted that before that, none of my plays were being registered back to my server (recents didn't show any of the tracks I'd played via ultrasonic).

Whilst enabling the scrobbling seems to have at least partially resolved this, if my phone is left to go to sleep during playback, eventually the app will stop the scrobbling until I wake the phone up again. Music playback still continues as normal here and is unaffected.

### Steps to reproduce

1. Setup Ultrasonic with a Funkwhale server (as each is different, if you need mine for testing, let me know)
2. Enable Scrobble to Last.fm (note, my server actually scrobbles to Listenbrainz but I imagine this is just pinging the Funkwhale server to then allow it to list the listen)
3. Start playing music (I started with a playlist of 500 tracks as I am currently on a night shift...)
4. Allow phone to enter sleep state and let music continue playing for a moment
5. Whilst playback is in situ, have the Funkwhale server UI open on another device, and regularly refresh the home page. The first few tracks under recent should be from Ultrasonic, but eventually it will stop updating.
6. Wake the phone up, keep the music playing
7. Refresh the page again and note that only the currently playing, or next track will be listed on the recent list.

## System information

 * **Ultrasonic version**: *2.18*
 * **Android version**: *11*
 * **Device info**: *Pixel 4*

## Additional notes

Please let me know if you require access to my instance for testing.

**Comment by nitehu** [comment]
Hmmm I can't see anything trivial in the code which would cause this. I've checked with my setup and Ultrasonic still scrobbles after  more than half an hour.

Could you please provide some info on when will the update stop? After a few songs or after a few hours?

When the scrobbling is disabled in Ultrasonic the server will generate its "recent" list from the songs Ultrasonic has requested from it. This should work independently from Ultrasonic, there is nothing magical in it, when Ultrasonic downloads a song the server knows it was downloaded and should update its recent list.
However, there is a catch: Ultrasonic will download usually 4-5 songs (but this is configurable) from your playlist as a buffer, so on your server the recent list should show a few songs which you haven't played yet! At least this is how it works in Ampache and Airsonic.

When the scrobbling is enabled, Ultrasonic will issue a scrobble request to the server, which looks something like this:

`2021-04-26 15:03:48.594 23643-8984/org.moire.ultrasonic.debug D/TimberOkHttpLogger: --> GET https://..../ampache/rest/scrobble.view?id=300050381&submission=true&u=nite&c=Ultrasonic&f=json&v=1.13.0&p=enc:.....`

This must be visible in the Android logcat, or in the debug log if you enable it in Ultrasonic settings.
This request also should be visible in your server logs.
It may happen that either Ultrasonic or your server had run into some problems while processing this request.

It would be really a great help if you could check the logs and see if there is any exception in them.
If you find that Ultrasonic has sent the scrobble.view request, and Funkwhale isn't updated, please check with the Funkwhale devs. It seems Funkwhale is in active development and [they have some open issues with scrobbling.](https://dev.funkwhale.audio/funkwhale/funkwhale/-/issues/1416)

**Comment by AMoonRabbit** [comment]
Hello Nitehu, thanks for the response. Okay, I will install log cat, and also start recording the logs on the server side to see if I can catch what's going on.

You mentioned that Ultrasonic will pre-load more than one song from the server depending on the configuration, currently this is set to 3, so I may tweak this setting to see how it affects the issue.

Now it's a given that Funkwhale isn't a sonic server but utilises the API to allow subsonic clients to connect. I think Funkwhale has a requirement for scribbles that a track is either more than 50% or fully played.

I will update this issue with my findings and the logs I produce.

**Comment by AMoonRabbit** [comment]
[FunkwhaleLogs030521.txt](https://github.com/ultrasonic/ultrasonic/files/6414874/FunkwhaleLogs030521.txt)
[logs-2021-05-03-13-41-46.zip](https://github.com/ultrasonic/ultrasonic/files/6414875/logs-2021-05-03-13-41-46.zip)

I've run a session this morning, hoping this helps shed some light on the issue.

**Comment by nitehu** [comment]
Sorry, I can't see any playback or scrobble related lines in the logs.
In Ultrasonic there is a setting to enable debug logging. This will create a file which contains all requests issued to the server. There you can see if Ultrasonic calls the scrobble.view, what is the response of the server, and if there was any exceptions.
I'm not sure how you can enable more detailed logs in Funkwhale.

**Comment by tzugen** [comment]
Closed for inactivity.
