### ISSUE TITLE
Ultrasonic notification should be dismissible by swipe

### ISSUE THREAD

**Issue by nitehu** [ultrasonic/ultrasonic#432]
Ultrasonic should work the same way as e.g. Youtube Music app. The new, modern MediaStyle notifications are working such a way that they aren't dismissible while the music plays. When the music is paused, the notification can be dismissed with a swipe.

The current solution has a dedicated "x" button to dismiss the notification. This is because on some phones (e.g. Samsung Note 9) Android kills the MediaPlayerService too agressively.

We must find a solution which works on most phones.

Also see the [discussion here](https://github.com/ultrasonic/ultrasonic/pull/421#issuecomment-823116549)

**Comment by tzugen** [comment]
This is fixed at least on the devices i can test with #726
