### ISSUE TITLE
Lock screen playback controls should include next/previous track

### ISSUE THREAD

**Issue by nitehu** [ultrasonic/ultrasonic#433]
## Problem description

Ultrasonic can be controlled from the phone's lock screen when the phone is locked by the phone's dedicated lock screen controls. 
On this UI the next / previous track buttons are currently disabled.

Ultrasonic should handle the next / previous buttons on the lock screen correctly.

### Steps to reproduce

- Start playback on Ultrasonic
- Lock the phone, check lock screen
- Next / Previous track buttons should be visible and working correctly

## Additional notes

This issue is a followup of the work done in [this PR](https://github.com/ultrasonic/ultrasonic/pull/421)

**Comment by SpcCw** [comment]
Also I noticed that now clicking on "Pause" button on lock screen while track is playing can not just pause music but also cause controls to disappear (as if Ultrasonic was shut down). However if I unlock the phone I still see Ultrasonic controls in notification drawer and can unpause playback. It doesn't happen every time too (sometimes lock screen pause button works correctly but about every other time this happens).

If it is not the same issue I can create separate one but it started to happen simultaneously.

**Comment by tzugen** [comment]
Hi, thanks for noticing!

I was planning to tackle this issue soonish, good to know what to look
out as well.

**Comment by tzugen** [comment]
@SpcCw  If you can build yourself you can tryout the PR I just added.
