### ISSUE TITLE
Android MediaStore API is broken in API >= 29

### ISSUE THREAD

**Issue by tzugen** [ultrasonic/ultrasonic#435]
There used to be two ways to add music to the Android Media Library.

1. Insert the data to the MediaStore with a reference to the Uri of the file in `MediaStore.MediaColumns.DATA`
2. Trigger a scan with `ACTION_MEDIA_SCANNER_SCAN_FILE`

Both of them have been deprecated with API 29.  And the deprecation in `ACTION_MEDIA_SCANNER_SCAN_FILE` tells to use the MediaStore. Lol....

So there seems to be no supported way to insert media files stored in our data directory to the Media Library. Maybe this is because Google is pushing `MediaBrowserService`?

Anyway, speculation aside, what shall we do? 

I think until we can get to implementing `MediaBrowserService`, which will be a bunch of work, it seems the only sensible thing is to stop inserting stuff into MediaStore on API >=29

**Comment by SaintDubious** [comment]
I'm not sure I understand the point of the Media Store. From the docs online it sounds like it's a way to make media available to other apps on your phone. But I'm not sure how that would be useful. I'm not going to listen to music on other apps. Is anyone aware of a customer use case that takes advantage of the Media Store?

**Comment by ogarcia** [comment]
I see `MediaBrowserService` interesting from point of view that is the standard to control audio apps and we must use it. The part of take media available to other apps on your phone is a good addon but we could live without it.
