### ISSUE TITLE
Improve five star rating

### ISSUE THREAD

**Issue by ogarcia** [ultrasonic/ultrasonic#440]
Subsonic API have two endpoints:
- `rest/star` -> Put a :star: in an album, artist or a song, is the same that say "I love it" or "I like it".
- `rest/setRating` -> Rate a song in a scale of 0 to 5 where 0 removes rating and 1 - 5 sets a rating. This only apply to music files.

For me this is something that should be dealt with separately. Right now the user can choose if he wants to use a one-star or five-star system, but I think we should differentiate one from the other. For example:
- Have a star button -> :star:  for like or not an album, artist or a song.
- Have a 5 hearts -> :heart: :heart: :heart: :black_heart: :black_heart: to set rating.

This can be related with #388

**Comment by nitehu** [comment]
Actually, Ampache solved this exactly the other way around:
![rating](https://user-images.githubusercontent.com/55684536/136600359-dc6e2679-6f9c-4dcb-9987-55ccc7114452.jpg)
This seems to be logical, as one could like or dislike a thing (heart), and give it 1-5 stars.
However, this would also mean the name of the "starred" items may be changed to "liked" to be consistent. Then again, I think other Subsonic servers use stars for liking... (I love how the subsonic API is mostly just inconsistent with everything, even with itself sometimes :)

Also, we may want to change the rating icons on the list items to something that takes up less space, something like:
![stars](https://user-images.githubusercontent.com/55684536/136601274-227745bf-16bf-4d3f-adff-7205f416b8e0.jpg)

**Comment by ogarcia** [comment]
Yes. The important point is use :heart: and :star: to differentiate one from the other. We can use :heart: to `rest/star` and :star: to `rest/setRating`.

I like the five star example. It can be a _button_ that shows a _popup menu_ to set level (or remove rating).

**Comment by tzugen** [comment]
We are moving to Gitlab. Please continue the discussion there: https://gitlab.com/ultrasonic/ultrasonic/-/issues/440
