### ISSUE TITLE
App crashes when pressing the album cover in player

### ISSUE THREAD

**Issue by punk3r70** [ultrasonic/ultrasonic#444]
## Problem description

The app crashes if the album cover is pressed in the "mini player" in the Ultrasonic Main view.

### Steps to reproduce

Start playback of a song or album. 
Navigate to Ultrasonic Main.
Press the album cover on the player at the bottom of the screen.
The app crashes.

## System information

 * **Ultrasonic version**: *2.20.0*
 * **Android version**: *11*
 * **Device info**: *Samsung, S21*

## Additional notes

Have seen this in earlier versions too but not had the time to report.

**Comment by tzugen** [comment]
See #415
