### ISSUE TITLE
Add more detail to "network error" message

### ISSUE THREAD

**Issue by nitehu** [ultrasonic/ultrasonic#470]
## Problem description

Ultrasonic should give more user-friendly and specific error messages for server connection related errors.
Currently every error just appears as "network error, check server address", but sometimes this isn't helpful at all.

At least we should differentiate 
- no response at all (real network error), 
- invalid response, 
- server errors. 

This would help the users and the devs too.

**Comment by tzugen** [comment]
We are moving to Gitlab. Please continue the discussion there: https://gitlab.com/ultrasonic/ultrasonic/-/issues/470
