### ISSUE TITLE
Use SafeArgs when navigation between fragments

### ISSUE THREAD

**Issue by tzugen** [ultrasonic/ultrasonic#510]
Right now we can be never completely sure, if any fragment gets passed the arguments it needs in the correct way.
This makes debugging difficult.

On a quick look, https://developer.android.com/guide/navigation/navigation-pass-data#Safe-args
should help

**Comment by tzugen** [comment]
(Happened to me in #506 )

**Comment by ogarcia** [comment]
@tzugen How is this? Please add this issue to any milestone (or backlog). Or close it if it is done :wink:

**Comment by tzugen** [comment]
We are moving to Gitlab. Please continue the discussion there: https://gitlab.com/ultrasonic/ultrasonic/-/issues/510
