### ISSUE TITLE
Release 2.21

### ISSUE THREAD

**Issue by tzugen** [ultrasonic/ultrasonic#513]
I think now with the last PR we have enough changes to make a new release.
What do you think?

**Comment by ogarcia** [comment]
Yez. When #368 is fixed we can close milestone and perform new release

**Comment by tzugen** [comment]
You think so? It is an old issue, which will be fixed in #514, but this is not ready yet, and I think we should not put too many changes in one commit, becuase if there is a problem it becomes harder to find out where it came from

**Comment by tzugen** [comment]
Ah, lol, It was me who gave this bug the wrong milestone. I put it to 2.22.X

**Comment by ogarcia** [comment]
Perfect, throughout today I make a new release

**Comment by ogarcia** [comment]
All done :wink:
