### ISSUE TITLE
Translations outdated

### ISSUE THREAD

**Issue by tzugen** [ultrasonic/ultrasonic#518]
The CI is pushing new strings to Transifex, but there is now scheduled updating of the strings that the community translated.
Looks like we last pulled in the new string over a year ago! 276429e

We should:
* Make more people maintainers of the transifex community (currently only one)
* Link Transifex with Github: 
* * Can be done here: https://www.transifex.com/ultrasonic/ultrasonic/settings/integrations/
* * Help: https://docs.transifex.com/transifex-github-integrations/github-tx-ui

**Comment by tzugen** [comment]
@ogarcia Can you make me admin on Transifex? Username should be the same.

**Comment by ogarcia** [comment]
@tzugen the translations are always pulled in every release, the last one was this e0f9059

We prefer not automate it because sometimes Transifex do _strange things_ and need a review in every pull.

I add you as project maintainer.

**Comment by tzugen** [comment]
Ah my mistake!
I was looking at the German ones, but then probably they didn't have changes..
