### ISSUE TITLE
Saving playlists does not work

### ISSUE THREAD

**Issue by Sohalt** [ultrasonic/ultrasonic#528]
## Problem description

Trying to save a playlist results in a toast with an error message about a non null parameter being null. The playlist is not saved. 

### Steps to reproduce

Queue some songs and try to save the queue as a playlist.

## System information

 * **Ultrasonic version**: 2.21.0
 * **Android version**: 11
 * **Device info**: Google Pixel 4a

**Comment by tzugen** [comment]
This is a bug I introduced in 2.21.
I would propose to release 2.2.2 after the Pr has been merged

**Comment by ogarcia** [comment]
@tzugen after merge #529 and #530 will perform a new release :wink:
