### ISSUE TITLE
parsing getbookmarks on ampache (i think i'm missing something)

### ISSUE THREAD

**Issue by lachlan-00** [ultrasonic/ultrasonic#548]
calls to the demo server return as not supported but only when you have a bookmark set.
```
https://demo.ampache.dev/rest/getBookmarks.view?u=ultrasonic_demo&c=Ultrasonic&f=json&v=1.13.0&t=&s=
```

i'm sure i'm missing something in the conversion but the raw data seems correct. i know there used to be a list of json examples somewhere but i can't find them any more. 

(very cool test window BTW)
![image](https://user-images.githubusercontent.com/1305249/126917391-40e0536a-7864-4c96-a901-283ace6dba63.png)

**Comment by lachlan-00** [comment]
It's probably average rating in the entry section but just need to check out a bit more

**Comment by Maxmystere** [comment]
Each test is made by doing the same request that you do when you open that specific view, so if it fails here I guess it failed in the bookmark window too but maybe i didn't get the perfect test url to know if it is implemented on server 
You can check the PR [here](https://github.com/ultrasonic/ultrasonic/pull/505/files#diff-2c0e9ab59e1de71ea0dd7d74fdf963a67093285fd99eb5669f69bfb5aea33d74R371)

**Comment by lachlan-00** [comment]
Found it. Looks like the entry is converted when it shouldn't. (Just a note for me to fix)
```
org.moire.ultrasonic.fragment.BookmarksFragment$LoadTask.doInBackground(SourceFile:372)
	at org.moire.ultrasonic.util.FragmentBackgroundTask$1.run(SourceFile:41)
 com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `org.moire.ultrasonic.api.subsonic.models.MusicDirectoryChild` out of START_ARRAY token
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 12, column: 26] (through reference chain: org.moire.ultrasonic.api.subsonic.response.BookmarksResponse["bookmarks"]->org.moire.ultrasonic.api.subsonic.response.BookmarkWrapper["bookmark"]->java.lang.Object[0]->org.moire.ultrasonic.api.subsonic.models.Bookmark["entry"])
```

**Comment by lachlan-00** [comment]
Not an ultrasonic bug

**Comment by lachlan-00** [comment]
fixed with https://github.com/ampache/ampache/commit/678d1876c95587af05b01dede051fa94b57bec24

bookmarks are the only object that shouldn't array the entry item
![image](https://user-images.githubusercontent.com/1305249/127239869-7193ceda-7a12-4e0b-b796-34bfc97aa69e.png)
