### ISSUE TITLE
Duration not read from metadata

### ISSUE THREAD

**Issue by welp-ops** [ultrasonic/ultrasonic#553]
If a subsonic server implementation does not return the correct duration for a song, Ultrasonic continues to display that incorrect duration in the scrubber even after the file header has been downloaded. Some other subsonic clients (eg dsub) do update the duration in the scrubber once the actual file metadata is available.

**Comment by tzugen** [comment]
It is a question whether we should provide for all bugs in some subsonic servers. For example we also rely on the other metadata returned from the server. Which server is providing these wrong durations and have you opened a ticket there?

**Comment by tzugen** [comment]
Fixed in #726

**Comment by welp-ops** [comment]
For context, the reason I open this issue is because I've been working on an experimental subsonic server that streams files over torrent. It is undesirable to start downloading every file in an album listing just to learn their durations. So my server just estimates the file duration based on file size and type.
