### ISSUE TITLE
Ultrasonic don't play flac files.

### ISSUE THREAD

**Issue by PrzemekSkw** [ultrasonic/ultrasonic#554]
## Problem description
I have music folder on my nextcloud server and I connect Ultrasonic to it. I can play MP3 files but when I try flac nothing happen.
The same situation od with Subsonic app.

## System information

 * **Ultrasonic version**: 2.21.0
 * **Android version**: 11
 * **Device info**: Motorola one vision

Regards,
Przemek

**Comment by tzugen** [comment]
I am using Airsonic as a server, and airsonic converts Flac -> Mp3 on
demand. I think most servers handle it like this.

**Comment by PrzemekSkw** [comment]
OK, I have some permissions problems.
Thanks.
