### ISSUE TITLE
Release 2.23

### ISSUE THREAD

**Issue by tzugen** [ultrasonic/ultrasonic#561]
I think it would be good to release 2.23 with Auto support to F Droid :)

**Comment by tzugen** [comment]
I cut a branch from develop from which to release:
https://github.com/ultrasonic/ultrasonic/tree/2.23

Because I want to keep the Oflline stuff for the next release.

**Comment by ogarcia** [comment]
Ok. I'll try to make a new release tomorrow. Too much work this week which the partners holidays.

**Comment by ogarcia** [comment]
@tzugen seems that CI is failing after change release numbe in assemble release step (OutOfMemoryError): https://app.circleci.com/pipelines/github/ultrasonic/ultrasonic/755/workflows/9206e358-e13f-40cf-8475-7afcfda5da42/jobs/1428

Do you know why can it be giving error? I try to increase memory but it still failing.

**Comment by tzugen** [comment]
I cherry picked a commit from another PR which fixes the CI

**Comment by ogarcia** [comment]
Yeah! I'll do the new release

**Comment by ogarcia** [comment]
Done! In Play Store the app has 96 as `versionCode` because with 95 the console fail with an _already published_ error. Maybe caused because I must accept Android Auto license terms.

In next version we must use 97 as `versionCode`.
