### ISSUE TITLE
Moving tracks up/down in the playlist view is difficult

### ISSUE THREAD

**Issue by moviuro** [ultrasonic/ultrasonic#569]
## Problem description

Trying to move tracks up/down in the playlist is difficult because:

* The right side of the view has a scroll bar, with a large hitbox
* The "slide" button is on the right of the track, under that large hitbox

### Steps to reproduce

Load a long playlist, try to move a track up/down

## System information

 * **Ultrasonic version**: *2.23.0*
 * **Android version**: *S Public Beta 4.1*
 * **Device info**: *Pixel 4a 5G*

## Additional notes

* https://gfycat.com/decentcoldchinesecrocodilelizard - Screen Capture
* Ideas to solve: move buttons around: `Title - Star - Move Button - Downloaded Arrow`. Or: `Move Button - Title - Star - Downloaded Arrow`

**Comment by nitehu** [comment]
Yep I think the drag handle should be on the left side.
