### ISSUE TITLE
Android Auto does not recognize Ultrasonic when not installed from Play Store

### ISSUE THREAD

**Issue by ryan-mcd** [ultrasonic/ultrasonic#575]
## Problem description

Android Auto does not find Ultrasonic as an available app.

### Steps to reproduce

Ultrasonic was installed via F-Droid, but Android Auto did not find Ultrasonic as an available app. I uninstalled and installed via the latest release APK, but Android Auto still does not find Ultrasonic as an available Android Auto App.

## System information

 * **Ultrasonic version**: 2.23.0
 * **Android version**: Android 11
 * **Device info**: Samsung Galaxy S10

**Comment by nitehu** [comment]
Unfortunatley none of us have a real Android Auto device so we could only test it in the emulator, where Ultrasonic works fine.

Would you help us get to the bottom of this?

It seems Android Auto by default may work only with apps downloaded from the Play Store. Here is how to [enable the developer mode](https://support.google.com/androidauto/thread/9008705/psa-how-to-enable-developer-mode-in-the-updated-android-auto-app?hl=en), which may help overcome this (also someone [mentions that "Unknown Sources" may be enabled](https://stackoverflow.com/questions/41284827/application-not-listed-in-android-auto) too)

Apps can still be missing, if they are not enabled or sleeping, [this guide has some tips](https://www.autoevolution.com/news/how-to-fix-apps-missing-from-the-android-auto-launcher-152751.html) fixing that.

If after all this Ultrasonic still doesn't work, could you please check if there is a crash log, or maybe retrieve a debug log (from logcat, or by enabling debug log in Ultrasonic settings) from the Ultrasonic directory (in Android/data)?

Let us know if there is any progress.

**Comment by Maxmystere** [comment]
I think it can be tested with [this app](https://play.google.com/store/apps/details?id=com.google.android.projection.gearhead.phonescreen)
But it will be deprecated in Android 12

**Comment by nitehu** [comment]
> I think it can be tested with [this app](https://play.google.com/store/apps/details?id=com.google.android.projection.gearhead.phonescreen)

That app already isn't compatible with my phones :(

**Comment by ryan-mcd** [comment]
I was unaware of the dev mode for Android Auto. I enabled it as well as unknown sources and can see Ultrasonic as an available app within the Android Auto app. I did not drive my car today, so I was unable to test the functionality, but I will verify tomorrow. Thank you for the info!

If successful, I would recommend making a note that in order to use Android Auto via APK or F-Droid, dev mode w/ unknown sources needs enabled within Android Auto.

**Comment by nitehu** [comment]
> If successful, I would recommend making a note that in order to use Android Auto via APK or F-Droid, dev mode w/ unknown sources needs enabled within Android Auto.

Thank you! This behaviour was new to me too, I will create a wiki page and link to it where necessary.

**Comment by ryan-mcd** [comment]
Success! At least with the APK. I'll give the F-Droid install a go tomorrow, because I would prefer to have F-Droid manage updates, but I see no reason why it won't work as it shows in the Android Auto after uninstalling the APK and installing from F-Droid.

That said, I noticed a couple of UI/UX oddities. Namely, when selecting a song whilst a playlist is playing, it swaps that song into the current playlist but does not drop the other songs. This is unmatched to the Ultrasonic App where that single song is loaded into the playlist. One could argue that it is actually beneficial for the playlist to be replaced by the rest of that album, or whatever is on the screen at that moment, starting with the selected song.
Another oddity/difference that is likely due to rendering of Android Auto is when random album is used, after selecting an album and hitting the "back" arrow, a new selection of albums are available.

All that said, these are incredibly minor. Thank you for the excellent app and the very exciting addition!

**Comment by nitehu** [comment]
> Namely, when selecting a song whilst a playlist is playing, it swaps that song into the current playlist but does not drop the other songs.

This is currently by design, if you select a single song to play it will be added to the list, while selecting multiple songs will replace the list. The intent was to minimize distraction while driving: there will be no awkward silence after playing a single song :)
It can be discussed what the user wants to hear after a single song, the rest of the playlist or the album where the song came from... maybe it should be a setting (or even a submenu after selecting a song with options like "add to playlist" or "play from here" or something similar).

> Another oddity/difference that is likely due to rendering of Android Auto is when random album is used, after selecting an album and hitting the "back" arrow, a new selection of albums are available.

Yes, the Android Auto API is a bit primitive, it just requests the content of nodes from Ultrasonic. If the node happens to be a random list, Ultrasonic can't easily find out that a new list should be retrieved from the server or it should somehow use older cached results. The current behaviour was the simplest, but it maybe worth improving.

Thank you very much for your feedback!
The Android Auto feature is very new and immature in Ultrasonic yet, we know that it will require more work in the future.

**Comment by ryan-mcd** [comment]
The F-Droid install works as well with Android Auto. In fact, it didn't even seem to think it was a different app. I'm going to close the issue. Thanks for working through this!
