### ISSUE TITLE
New point release?

### ISSUE THREAD

**Issue by tzugen** [ultrasonic/ultrasonic#576]
Version 96 was good, except one exception that Nite has fixed in develop.
Should we make a point release (2.23.1) and release that on the Playstore?

**Comment by tzugen** [comment]
In case you think its a good idea, the develop branch was at https://github.com/ultrasonic/ultrasonic/commit/225bb7826302fa2b929ec4b28f4b8b18fe24b1d7 when I wrote this.

**Comment by tzugen** [comment]
Maybe it would be then good to backport this commit https://github.com/ultrasonic/ultrasonic/commit/225bb7826302fa2b929ec4b28f4b8b18fe24b1d7 onto the 2.23 tag

**Comment by ogarcia** [comment]
What do you prefer, new version 2.23.1 with only #571 to master or a full version 2.24.0 with current develop?

**Comment by tzugen** [comment]
I prepared a branch (2.23.1) for the point release.
2.24.0 can be cut from current develop.

I would suggest this:
2.23.1 ( 5ef3ced1 )  -> Playstore Release track
2.24.0 ( 950691d ) -> F-Droid and Playstore testing track

**Comment by ogarcia** [comment]
Done 2.23.1. Will wait until weekend before move it from testing to release.

**Comment by ogarcia** [comment]
This week I'm out (vacation time). If you want in next week we can make a new release

**Comment by ogarcia** [comment]
I think that we can release 2.24.0 after merge #593 and #594

What do you think?

**Comment by tzugen** [comment]
Yes sounds good.
We should also check the play console if new exceptions are shown up in the last release.

**Comment by tzugen** [comment]
I suggest not adding the sidebar PR to 24,
otherwise it will become quite large again.
Let's just finish the open PRs and release 24,
and do the larger visual changes in the next

**Comment by ogarcia** [comment]
@tzugen Ok. Then after merge #596 and #602 we can do a new release

**Comment by tzugen** [comment]
Ok, its reasdy :)

**Comment by ogarcia** [comment]
All done!
