### ISSUE TITLE
ALAC/MP4 does not play on some phone, plays fine on others

### ISSUE THREAD

**Issue by palijn** [ultrasonic/ultrasonic#577]
## Problem description

When playing ALAC/MP4 files, the player looks like it starts to play, and stops.
The weird thing is : this only happens on my Google Pixel3a phone . Playing works fine on my more recent Oppo phone.
I would have thought that Ultrasonic would play all music files juste the same on any android phone ?
If a subcomponent is missing or malfunctioning, maybe at least inform about the case in an error message ?

### Steps to reproduce

Encode ALAC songs in an MP4 format (iTunes does that). 
Put them under Airsonic share, connect to the Airsonic server. 
Disable MP3 encoding for the player that will be used in the next step (Ultrasonic on that phone).
On Ultrasonic, search for the song, add to playlist and play.
On a Google Pixel3a, the song will not play.
(On an Oppo A72, the song plays. Both run Android 11.)

## System information

 * **Ultrasonic version**:  2.22.0 on Google Play 
 * **Android version**: 11
 * **Device info**:  Google Pixel 3a

**Comment by nitehu** [comment]
Ultrasonic uses the OS's built-in Android media player to play music files, in itself it doesn't contain any codecs. 
I can imagine that the compatibility may vary between phones.
To get to the bottom of this, could you please check us that
- is the file you mentioned playable in other media player apps on the phones? Only Ultrasonic has this problem?
- are there any exceptions in the logcat or Ultrasonic debug logs (in the android/data folder)?

Meanwhile I suggest to set up transcoding these files to FLAC on your server, as that hasn't any compatibility issues AFAIK.
