### ISSUE TITLE
Add CI integration.

### ISSUE THREAD

**Issue by Tapchicoma** [ultrasonic/ultrasonic#6]
Discuss and implement CI for this project.

Current minimum requirements: run plain java tests.

But keep in mind that in the future this project will also need to run android instrumentation tests and ui tests.

**Comment by Tapchicoma** [comment]
Possible candidates:
- [travis](https://travis-ci.org/)
- [drone](https://drone.io/)
- [circleci](https://circleci.com/)

**Comment by ogarcia** [comment]
Any of three candidates are good for CI, but for Drone we have make an install of it in a private server. IMHO I think that is better travis or circle. Between these two options, we can use any of both.

Another tool that we can use is [Codacy][1], but only for Java, Kotlin is not supported for now.

[1]: https://www.codacy.com

**Comment by Tapchicoma** [comment]
Codacy looks like reimplementation  of Sonarqube and may not be so configurable as common CI.

Drone indeed requires to use self hosted installation, so better not use it.

**Comment by ogarcia** [comment]
No, Codacy is only for code analysis, for CI we must use Travis or Circle.

**Comment by Tapchicoma** [comment]
Checked both travis and circleci.

Both proposing free plans for opensource projects.

Both can use docker images.

Checked documentation and it seems that circleci has simpler docker configuration, caching between the builds and prebuilt android images.

**Comment by ogarcia** [comment]
Ok, in this case, we use circleci. You can login in with your github account and must see this repository in ultrasonic organization.

**Comment by Tapchicoma** [comment]
> Contact repo admin

@ogarcia I don't have enough rights to add this project to the CircleCI. Can you do it? And I will then add CI config.

**Comment by ogarcia** [comment]
@Tapchicoma done!

**Comment by Tapchicoma** [comment]
For now added minimal CI config. Further improvements can be done in separate tickets.
