### ISSUE TITLE
Support runtime permissions

### ISSUE THREAD

**Issue by Tapchicoma** [ultrasonic/ultrasonic#79]
In order to update api level app should support runtime permissions.

Currently app uses following `dangerous` permissions:
- android.permission.WRITE_EXTERNAL_STORAGE
- android.permission.READ_EXTERNAL_STORAGE

**Comment by Tapchicoma** [comment]
This permission is only required when user defines non-default cache location. 

The problem is that current setting for this requires typing full path to desired cache folder (for example `/sdcard/ultrasonic`) and it is not very usable. 

I am considering removing this setting, removing permission and just use device app private location on external storage for cache.

@ogarcia will such approach be ok?

**Comment by Tapchicoma** [comment]
Created separate ticket for this setting: #98

**Comment by ogarcia** [comment]
As I say in #98 IMHO I think that the first approach must be a simple selector that permits choose between internal storage and sdcard

**Comment by ogarcia** [comment]
@Tapchicoma I add `help wanted` label in case someone wants to help with a PR :wink:

**Comment by Tapchicoma** [comment]
@ogarcia sorry, don't really have time for addressing main blocker for now to advance app further - how to migrate from current caching approach to new one that will not require storage permission (kind of a lot changes) :disappointed_relieved: 

This is one of the "need-to-do" for bumping app target version to latest one and re-enable publishing it to play store.

**Comment by ogarcia** [comment]
@Tapchicoma no problem, this is a voluntary project and we always have periods without free time. If someone can help us perfect, if not, then it will be addressed in the future. :blush:
