### ISSUE TITLE
F-Droid build?

### ISSUE THREAD

**Issue by pR0Ps** [ultrasonic/ultrasonic#83]
I've submitted [a merge request](https://gitlab.com/fdroid/fdroiddata/merge_requests/2676) for this app to be included in [F-Droid](https://f-droid.org/), a Free and Open Source Android App Repository. Please let me know (or make a comment on the MR) if you're comfortable with this inclusion or not.

**Comment by Tapchicoma** [comment]
F-Droid faq for developers: https://f-droid.org/en/docs/FAQ_-_App_Developers/

**Comment by Tapchicoma** [comment]
@pR0Ps I am not very familiar with F-Droid publishing. As I understand it will automatically build every new commit with tag to master branch on F-Droid CI and then publish to F-Droid?

Maybe better to specify tag pattern. Something like `release_.*[0-9]$`

**Comment by pR0Ps** [comment]
@Tapchicoma It uses the tags to check for new versions. When it finds a new tag it will automatically check if the app's `versionCode` has been updated. If it has, it will build that version of the app and deploy it to the F-Droid repo.

It didn't seem like tags were created for anything but bumping versions so I didn't specify a regex for them. It's possible to do so though: https://f-droid.org/docs/Build_Metadata_Reference/#Update-Check-Mode

**Comment by pR0Ps** [comment]
@Tapchicoma @ogarcia: Everything checks out with the F-Droid merge request, just waiting for your sign-off on the inclusion.

**Comment by Tapchicoma** [comment]
I approve inclusion.

**Comment by ogarcia** [comment]
Ok for me

**Comment by pR0Ps** [comment]
Thanks guys, I've notified F-Droid and it should be merged shortly. I'll close this out when that happens.

**Comment by Tapchicoma** [comment]
@pR0Ps as I understand F-Droid will automatically build and publish app on every night, but I still can't find Ultrasonic in catalogue. Can you point me why is it?

**Comment by pR0Ps** [comment]
[It's been built with no issues](https://f-droid.org/wiki/page/org.moire.ultrasonic) and is just waiting for the next repo index update (hopefully today).
