### ISSUE TITLE
Automate publishing the app

### ISSUE THREAD

**Issue by Tapchicoma** [ultrasonic/ultrasonic#84]
Would be nice if new version of the app can be automatically published by CI.

We can use following plugin to do it: https://github.com/Triple-T/gradle-play-publisher
It supports Google Play Store and F-Droid (see #83).

Automatic publishing can be done on every merge to master branch (?)

**Comment by ogarcia** [comment]
Is a good idea, but I think that is better use tags than every merge into master. Every new tag with version number is published in Google Play and F-Droid.

**Comment by ogarcia** [comment]
This can be close for now. Only in play store must be published by hand, but prefer this method since Google continuosly change things in the store.
