### ISSUE TITLE
Server settings

### ISSUE THREAD

**Issue by Tapchicoma** [ultrasonic/ultrasonic#90]
Rethink how app shows and manages server settings.

Problems so far:
1. App shows modal dialogue for each field that user wants to edit.
2. App saves server settings in `SharedPreferences`, better to save them into DB.
3. List of servers are added to the app settings.

This issue is an epic issue. Particular changes should be done in a separate issues.

**Comment by ogarcia** [comment]
For enter server settings we have two options, or leave it like is current (a modal dialog for each field) or use a form style like JuiceSSH.

A list of servers with a fancy add button:
![image](https://user-images.githubusercontent.com/572924/34199338-be7ebc06-e56d-11e7-87fe-a7ac673f20b9.png)

And when you press in add button a form that ask for settings:
![image](https://user-images.githubusercontent.com/572924/34199290-98a4915e-e56d-11e7-904e-b8bce11e321c.png)

PS: Sorry for screenshots language, I have my phone in Spanish 😄
