### ISSUE TITLE
Add option to start playback on insertion of headphones

### ISSUE THREAD

**Issue by craftyguy** [ultrasonic/ultrasonic#93]
This is a request to have an option for starting playback when headphones are connected. It seems the app will already (correctly, IMHO) stop playback when the headphones are disconnected, so perhaps this would be trivial to implement for someone who was not a total android app novice like me!

I know the readme says this project is stalled, but I see a lot of excellent activity and hopefully it keeps up! I really like this app!

**Comment by Tapchicoma** [comment]
I haven't yet looked into app playback code. My intention for future is to migrate app to use [ExoPlayer](https://github.com/google/ExoPlayer).

If it is easy to implement this FR in current implementation - I will add it, otherwise it will be added after migrating.

**Comment by craftyguy** [comment]
@Tapchicoma no problem, sounds like a great idea! thank you for reviving this project! :)

**Comment by craftyguy** [comment]
So I just took a REALLY quick look at the code, looks like headset intent is handled here, and perhaps it's as easy as adding another condition to handle when the headset is plugged in (plus adding an option to settings for toggling this): https://github.com/ultrasonic/ultrasonic/blob/5fee79c652ab395b4e71e3a560454d2d1922165f/ultrasonic/src/main/java/org/moire/ultrasonic/service/DownloadServiceLifecycleSupport.java#L147

**Comment by Tapchicoma** [comment]
Yeah, seems no so much work.


 Also I am considering adding App setting for this autoresume. What do you think?

**Comment by craftyguy** [comment]
So basically an app setting to automatically resume playback when headphones are connected? I thought that was what I was asking for originally (but I used different wording I guess), in any case, it sounds like a great idea :)

**Comment by Tapchicoma** [comment]
Added setting (disabled by default) to enabled playback resume on headphone insertion. This will be available in next release. Feel free to reopen if this will not work for you.
