### ISSUE TITLE
Reimplement custom cache folder setting

### ISSUE THREAD

**Issue by Tapchicoma** [ultrasonic/ultrasonic#98]
## Problem description

To use custom cache folder user needs to type path on the device (for example `/sdcard/ultrasonic`) that requires advanced Android knowledge and not user-friendly.

App need to introduce another way to set cache folder.

*Note:* using external storage will require granting runtime permission.

## Possible Improvements:
- Select cache folder for each server individually
- Provide dialog or separate screen to select desired cache folder (user may want to create a new one)
- Call external app to do this selection.
- Request permission before selecting the folder.

**Comment by ogarcia** [comment]
@Tapchicoma There is a lot of people that say in the comments that they want use an external storage (sdcard) for Ultrasonic cache. Is true that the actual method is not user friendly.

As you say in #79 is a good idea remove dangerous permissions and request it only if the user wants use non-default cache location.

By default the app may have a simple selector for use internal storage or sdcard and an advanced setting for define "by hand" (or using external browser app) the cache path.

Another improvement may be the possibility of delete a full album or artist from cache.

Even redefine the controllers _pin_, _unpin_ and _download_ that not is clear. I think that _pin_ implies download and _unpin_ implies delete but, at this moment, the app not works like that.

**Comment by Whisprin** [comment]
This is how it looks currently in [DSub](https://github.com/daneren2005/Subsonic): [Cache location](https://user-images.githubusercontent.com/3153136/34182769-e89d1cea-e517-11e7-9475-503ae6dc4a09.png)
But adjusting this path, which is writeable by the app without requesting special permissions, to match Ultrasonic brings up an error message and resets the path to default. I'm running Android 8.0.

Additionally `/sdcard/ultrasonic` works but is on _internal_ memory.

An up to date implementation to request rw access to the _external_ memory can be found in the [Amaze file manager](https://github.com/TeamAmaze/AmazeFileManager).

**Comment by ogarcia** [comment]
The DSub idea is good, but I think that instead of show location by default, have a selector with 3 options, Internal, External and _Advanced manual selection_. If you enter in last option then show the path and give the possibility of change it.

**Comment by Tapchicoma** [comment]
To make it easier to update, let's go with selector that have 2 entries:
- Internal storage (app private internal storage)
- External storage (app private external storage)

Later if there will be request from users app can introduce 3rd option "Custom location"
